import json
from pathlib import Path

OUT = Path('outputs')
OUT.mkdir(exist_ok=True)
tasks=[]
def add(key,phase,title,goal,action,steps,accept,impact,deps='',refs='',questions='',owner='Engenharia',kind='Desenvolvimento'):
    tasks.append(dict(key=key,id=f'BK-{len(tasks):03}',phase=phase,title=title,goal=goal,action=action,steps=steps.split(' || '),accept=accept,impact=impact,deps=deps.split() if deps else [],refs=refs,questions=questions,owner=owner,kind=kind,status='Não iniciada',evidence='',weight=1))

p='00 Descoberta e decisões'
add('baseline',p,'Confirmar a base de escopo e as decisões da Majucau','Ter uma referência única para construir o produto.','Registrar escopo, responsáveis e decisões pendentes.','Registrar Go, React JS, DDD hexagonal monolítico, uso só Majucau e hospedagem local || Confirmar todos os módulos da primeira produção || Resolver divergências caso a caso e registrar autor, data e referência', 'Majucau revisou o escopo e cada decisão tem resposta ou bloqueio explícito.','Evita construir uma regra ou módulo diferente do esperado.',refs='Pedido do usuário; 00_Resumo; C_Conflitos; D_Lacunas',questions='Todas as decisões em aberto',owner='Majucau + Arquitetura',kind='Planejamento')
add('inventory',p,'Inventariar os materiais e suas versões','Saber exatamente o que foi analisado.','Catalogar as imagens, abas e documentos citados.','Listar 16 PNGs e 20 abas || Registrar duplicata T10 por hash e materiais ausentes || Preservar originais e vincular requisitos às coordenadas da planilha','Inventário identifica 15 imagens únicas, todas as abas e documentos apenas referenciados.','Evita omissões e mistura de versões.',refs='Pacote fornecido; manifesto de arquivos',owner='Produto + UX',kind='Planejamento')
add('repoaudit',p,'Verificar o ponto de partida no GitHub','Separar trabalho existente de trabalho futuro.','Inspecionar repositório, commits, arquivos e issues.','Consultar repositório em modo leitura || Registrar resposta de repositório vazio || Perguntar se há código ou ambientes fora do GitHub','Estado do GitHub comprovado; eventual material externo registrado como não inspecionado.','Permite planejar a preparação do projeto desde o início.',refs='GitHub majucau /contents e /commits',owner='Arquitetura',kind='Planejamento')
add('visualaudit',p,'Auditar cada tela e seus cálculos ilustrativos','Transformar imagens em comportamentos verificáveis.','Mapear cartões, tabelas, gráficos, filtros, links, mensagens e inconsistências.','Percorrer cada imagem e suas notas || Conferir somas, percentuais, datas, unidades e estados || Registrar conflitos sem escolher silenciosamente uma referência','Cada tela possui inventário e achados, com destino no backlog.','Reduz erros que passariam despercebidos numa reprodução visual.',deps='inventory',refs='Todas as imagens; CEIs T11–T17',owner='UX + Produto + QA',kind='Planejamento')
add('missing',p,'Completar o escopo sem imagem ou com referência antiga','Definir as telas ainda insuficientemente especificadas.','Obter e conferir T01, T11, Aplicações e os blocos adicionais citados.','Solicitar mockup Compras e Visão Executiva || Confirmar Aplicações, Pricing, Logística, Simuladores, Relatórios, Produtos e Balanço Patrimonial || Reconciliar a numeração antiga da matriz com a atual','Mapa de navegação aprovado cobre todos os módulos exigidos; nenhum item é removido por suposição.','Impede declarar produção completa com módulos faltantes.',deps='inventory',refs='A_Matriz_Mestra!A41:S41; 00_Resumo!A46:D46; menus das imagens',questions='Q-01,Q-02',owner='Majucau + UX',kind='Planejamento')
add('partial',p,'Decidir a regra de pagamento com valor diferente','Ter uma única semântica de baixa de títulos.','Resolver o conflito C-01.','Apresentar título de R$ 1.000 e movimento de R$ 600 || Registrar saldo, estado e efeito no caixa para a regra escolhida || Definir estorno, excesso, desconto, tarifa e parcelamento','Exemplos aprovados produzem um único saldo e estado por evento.','Afeta contas a pagar, vencidos, caixa e conciliação.',refs='C_Conflitos!A3:L3; T04',questions='C-01',owner='Majucau / Financeiro',kind='Planejamento')
add('investmentpolicy',p,'Fechar os critérios da calculadora de aplicação','Permitir um cálculo reproduzível e compreensível.','Resolver fonte do lucro, semana crítica, posição de caixa e período elegível.','Decidir C-02 e C-03 || Definir L-07, semana/calendário, empates, reserva, CDI Plus e saldo transferível || Reconciliar fórmula da matriz com memória da T08 e casos de entrada faltante','Exemplos aprovados incluem lucro negativo, reserva insuficiente, M−2, janeiro e dados antigos; saída bloqueia quando necessário.','Evita uma capacidade de aplicação baseada em critérios indefinidos.',refs='C_Conflitos!A4:L5; A_Matriz_Mestra!A32:S36; T02/T08',questions='C-02,C-03,L-07,Q-10',owner='Majucau / Financeiro',kind='Planejamento')
add('accountingpolicy',p,'Definir competência, fontes e classificações financeiras','Fixar a origem e o período de cada linha da DRE e do balancete.','Resolver custos históricos, perdas, juros, fretes, tributos e saldos iniciais.','Obter amostras e plano de contas || Definir L-03,L-04,L-05,L-08,L-09,L-13,L-14 por tipo de evento || Aprovar exemplos de reabertura, correção e estorno','Cada linha material tem fonte, conta, competência, contrapartida quando aplicável e tratamento de ausência.','Previne resultado incompleto apresentado como definitivo.',refs='D_Lacunas; M-017..M-029',questions='L-03,L-04,L-05,L-08,L-09,L-13,L-14,Q-09',owner='Majucau / Financeiro',kind='Planejamento')
add('opsrules',p,'Definir regras pendentes de estoque, produção e compras','Eliminar critérios operacionais ambíguos.','Homologar pedidos aplicáveis, metas, quantidades e prioridades.','Definir saldo utilizável, depósito, unidade e pedido aberto aplicável || Decidir significado de Em andamento e Abaixo da meta na T10 || Fechar fórmula de quantidade, prazo histórico e prioridades da T11','Casos de igualdade ao mínimo, pedido parcial/cancelado, meta zero/ausente e unidades distintas têm resultado aprovado.','Evita compra duplicada e avaliação incorreta da produção.',refs='T09/T10; Q_CEI_Tela_11',questions='L-17,L-18,Q-07,Q-08',owner='Majucau / Operação',kind='Planejamento')
add('forecastpolicy',p,'Homologar regras de estudo, metas e qualidade de projeção','Definir quando uma projeção pode ser utilizada.','Fechar métricas, limites, distribuição de metas e produção derivada.','Aprovar calendário sazonal e séries com pouco histórico || Definir limites WAPE/Bias/MASE e preço/mix/overrides || Resolver quantidades de produção da imagem versus regra textual e relação entre metas T10/T12','Conjunto de exemplos por SKU/mês fecha vendas, produção, estoque e faturamento; critérios de qualidade ficam versionados.','Impede metas irreconciliáveis e métricas de qualidade fictícias.',refs='R_CEI_Tela_12; T12; M-045..M-049',questions='L-20,L-21,Q-11,Q-12',owner='Majucau / Planejamento',kind='Planejamento')
add('filecontracts',p,'Obter arquivos reais e homologar contratos de importação','Conhecer os formatos que o sistema realmente receberá.','Mapear Bling, Nuvem Pago, Nuvem Envio, extratos, perdas, ajustes e demais fontes ativas.','Receber amostras com dados protegidos quando necessário || Mapear colunas, IDs, tipos, sinais, datas e versões || Definir pasta, cópia imutável, periodicidade, descarte, rejeição e atualização','Cada fonte ativa tem amostra, responsável e contrato; ausência de arquivo não significa ausência de movimento.','Evita importações que duplicam ou perdem dados.',refs='H_Contrato_Dados; U_CEI_Tela_15',questions='L-11,L-12,L-24,Q-06',owner='Majucau + Engenharia de Dados',kind='Planejamento')
add('cocoapolicy',p,'Definir fontes e critérios dos sinais do cacau','Tornar os sinais externos comparáveis e rastreáveis.','Homologar fontes de preço, câmbio, clima, safra e estoques globais.','Mapear origens reais dos fornecedores || Definir unidades, câmbio, datas e comparabilidade do preço || Aprovar thresholds, validade dos dados e custo/licença de acesso','Cada sinal tem fonte, origem geográfica, regra e tratamento de dado insuficiente.','Evita oportunidade ou risco calculados sobre bases incompatíveis.',refs='Q_CEI_Tela_11; H_Contrato_Dados!A21:H22',questions='L-19',owner='Majucau / Compras',kind='Planejamento')
add('actionpolicy',p,'Definir exportações, ações e resolução de pendências','Especificar o que cada botão pode fazer.','Fechar matriz de ações por tela e fluxo de resolução por tipo.','Definir destinos de Ver detalhes, Ajuda e atualização || Decidir exportações T02–T07 e T13–T15, filtros, colunas e permissões || Definir resolução com evidência sem baixa genérica de pendência','Todo controle visível tem comportamento aprovado, indisponibilidade explicada ou decisão pendente identificada.','Evita botões decorativos e encerramento indevido de problemas.',refs='S/T/U CEIs; T02–T07; T13–T15',questions='L-22,L-23,Q-13',owner='Majucau + UX',kind='Planejamento')
add('accesspolicy',p,'Homologar acesso, perfis e edição de parâmetros','Definir quem pode consultar ou alterar cada recurso.','Fechar matriz ação por módulo e ciclo de vida de usuários.','Validar ADMIN, FINANCEIRO, OPERAÇÃO e LEITURA || Definir login, MFA, convite, recuperação, expiração e revogação || Aprovar edição/vigência/rollback de cada parâmetro crítico','Matriz distingue consulta, exportação, reprocessamento, metas, parâmetros e usuários; bloqueado não acessa.','Reduz acesso indevido e mudança de regra sem rastreio.',refs='W/Y CEIs; H_Contrato_Dados!A34:H39',questions='L-25,L-26,Q-14',owner='Majucau + Segurança',kind='Planejamento')
add('localrequirements',p,'Levantar a infraestrutura local e a rotina de uso','Dimensionar uma instalação que a Majucau consiga operar.','Registrar equipamento, rede, disponibilidade e responsáveis.','Identificar SO, CPU, RAM, disco, energia e internet || Confirmar acesso local/remoto, dispositivos e usuários simultâneos || Definir tolerância a parada, perda de dados, horários de manutenção e operador','Ficha de infraestrutura aprovada inclui backup separado, restauração esperada e forma de suporte.','Evita depender de um computador sem capacidade ou sem recuperação.',refs='Pedido: hospedagem local',questions='Q-03,Q-04,Q-05,Q-15,Q-16',owner='Majucau + Infraestrutura',kind='Planejamento')
add('deliveryplan',p,'Organizar responsáveis, estimativas e marcos de entrega','Manter evolução visível sem prometer prazos sem base.','Revisar dependências e estimar esforço com a equipe.','Confirmar prazo e disponibilidade de pessoas || Subdividir tarefas grandes e atribuir pesos de esforço || Definir marcos internos e um único lançamento com todos os módulos homologados','Backlog sem dependências circulares, dono por tarefa e cronograma apoiado em capacidade real.','Permite acompanhar avanço e antecipar bloqueios.',deps='baseline missing localrequirements',refs='Pedido do usuário; G_Ordem',questions='Q-17',owner='Majucau + Liderança técnica',kind='Planejamento')

p='01 Arquitetura e UX'
add('domainmap',p,'Modelar os domínios e o vocabulário do negócio','Separar regras sem fragmentar a aplicação em serviços.','Desenhar contextos do monólito e suas responsabilidades.','Modelar Tesouraria, Conciliação, Resultados, Operação, Planejamento, Integrações e Acesso || Definir entidades, agregados, invariantes e eventos || Compartilhar contratos e IDs, evitando modelos únicos gigantes','Mapa mostra dono de cada fato, dependências direcionais e transações de negócio.','Evita regras duplicadas entre telas e módulos.',deps='baseline partial investmentpolicy accountingpolicy opsrules forecastpolicy',refs='A_Matriz_Mestra; B_Intersecoes; H_Contrato_Dados',owner='Arquitetura')
add('hexagonal',p,'Definir a estrutura hexagonal do monólito Go','Manter regras testáveis e independentes das integrações.','Registrar portas, casos de uso e adaptadores.','Separar domínio, aplicação e adaptadores por módulo || Definir portas de repositório, relógio, arquivos e provedores || Documentar composição única, fronteiras de transação e dependências permitidas','Domínio não depende de HTTP, React, ORM ou clientes Bling; módulos se comunicam por contratos.','Facilita manutenção e substituição de integração.',deps='domainmap',refs='Stack definida pelo usuário',owner='Arquitetura')
add('storage',p,'Definir persistência, migrações e precisão dos dados','Preservar dinheiro, quantidades e histórico corretamente.','Avaliar PostgreSQL local e modelo relacional por domínio.','Definir valores monetários exatos e arredondamento por regra || Modelar chaves, índices, constraints, versões e transações || Escolher migrações e política de compatibilidade de versões','Modelo diferencia ausência de zero e proíbe duplicatas de negócio; decisão de banco é registrada.','Evita erros de centavos e corrupção lógica de fatos.',deps='domainmap filecontracts',refs='H_Contrato_Dados; proposta técnica',owner='Arquitetura + Dados')
add('apicontract',p,'Descrever contratos de API e estados de leitura','Unir React e Go com respostas previsíveis.','Documentar endpoints, ações, filtros e erros em OpenAPI.','Definir paginação, ordenação, datas, moeda e unidade || Incluir posição, origem, qualidade, versão e autorização || Diferenciar validação, falta de dado, conflito, acesso negado e falha de fonte','Exemplos por tela permitem testar cliente e servidor antes da integração real.','Reduz retrabalho de interface e interpretação incorreta.',deps='hexagonal actionpolicy accesspolicy',refs='H_Contrato_Dados; todos CEIs',owner='Full Stack')
add('dataquality',p,'Modelar estado, proveniência e consistência entre telas','Explicar a confiabilidade de cada número.','Separar status do negócio, qualidade do dado e processamento.','Mapear CONFIRMED, PROJECTED, STALE, UNAVAILABLE e demais estados || Definir cobertura, data de posição e snapshot consistente || Definir propagação de qualidade sem transformar ausência em zero','Mesma consulta e posição produzem mesmos totais; dados parciais e antigos ficam identificados.','Impede que uma tela pareça atualizada quando sua fonte falhou.',deps='storage apicontract',refs='M-002,M-037,M-038; H_Contrato_Dados')
add('designsystem',p,'Consolidar o padrão visual e a navegação','Traduzir os mockups para componentes consistentes.','Especificar tokens, componentes e mapa de rotas.','Comparar logos, menus, agrupamentos, títulos e rótulos || Registrar cada diferença para decisão Majucau || Definir tabelas, cartões, filtros, gráficos, badges e estados de seleção','Biblioteca de especificações preserva escolhas aprovadas; menu aponta para a tela certa.','Corrige inconsistência de navegação sem redesenho silencioso.',deps='visualaudit missing actionpolicy',refs='Todas as imagens; M-039,M-050',questions='Q-01,Q-02,Q-18',owner='UX')
add('uxstates',p,'Especificar acessibilidade, telas pequenas e estados de exceção','Permitir uso além da imagem estática.','Desenhar loading, vazio, erro, bloqueado e dados antigos.','Definir navegação por teclado, foco, rótulos e mensagens || Testar legibilidade, zoom, contraste e leitura de tabelas largas || Submeter ajustes estruturais e telas ausentes à Majucau','Fluxos completos cobrem falhas e permissões; nenhuma informação depende só da cor.','Reduz erros de operação e dificuldade no uso diário.',deps='designsystem localrequirements',refs='Todas as imagens; gaps UX',questions='Q-18',owner='UX + QA')
add('analyticschoice',p,'Decidir a necessidade de Python e Streamlit','Adicionar ferramentas somente quando houver benefício verificável.','Planejar avaliação de importação e projeções com dados representativos.','Comparar processamento Go com Python para cargas e séries reais || Avaliar pandas ou Polars conforme memória, formato e tempo medidos || Manter React como interface principal; documentar eventual uso interno de Streamlit','Decisão registra ganho, custo de operação e contrato de entrada/saída; sem segundo motor financeiro.','Controla complexidade e mantém uma fonte de regras.',deps='hexagonal forecastpolicy filecontracts localrequirements',refs='Sugestão permitida pelo usuário; proposta técnica',owner='Arquitetura + Dados')
add('threatmodel',p,'Planejar segurança e proteção dos dados','Identificar falhas possíveis antes de expor o sistema.','Mapear acessos, arquivos, credenciais e fronteiras da rede.','Classificar informações e privilégios || Avaliar importação maliciosa, acesso direto à API e exposição de segredos || Definir retenção, restauração e controle de dados usados em testes','Riscos têm tratamento e testes associados; nenhuma credencial entra no Git ou no navegador.','Protege os dados financeiros e operacionais.',deps='accesspolicy localrequirements apicontract',refs='M-058; Y_CEI_Tela_17',owner='Segurança + Arquitetura')

p='02 Fundação do projeto'
add('repoinit',p,'Preparar o repositório e as convenções do projeto','Criar uma base reproduzível para a equipe.','Inicializar estrutura, documentação e políticas do Git.','Criar README, ignore de segredos e regras de contribuição || Organizar backend, frontend, docs e infraestrutura conforme decisão || Configurar revisão e permissões do repositório','Novo desenvolvedor encontra instruções e convenções; histórico contém somente artefatos do projeto.','Evita configuração informal e exposição de arquivos locais.',deps='repoaudit hexagonal deliveryplan',refs='GitHub vazio; BK arquitetura')
add('devsetup',p,'Preparar o ambiente de desenvolvimento local','Permitir execução reproduzível fora da produção.','Documentar versões e comandos de instalação, execução e limpeza.','Fixar dependências e arquivos de lock aplicáveis || Criar configuração exemplo sem segredos e dados sintéticos || Validar início em máquina limpa','Ambiente sobe seguindo documentação e não acessa dados de produção por padrão.','Diminui tempo perdido com diferenças entre máquinas.',deps='repoinit storage localrequirements')
add('gofoundation',p,'Criar a fundação do backend Go','Dispor de processo executável com as fronteiras planejadas.','Implementar composição, configuração, servidor e ciclo de vida.','Validar configuração ao iniciar || Implementar timeouts, cancelamento, desligamento e health/readiness || Montar módulos por injeção explícita de dependências','Processo inicia e encerra sem interromper operações silenciosamente; configuração inválida é identificada.','Sustenta todas as funcionalidades.',deps='devsetup hexagonal')
add('reactfoundation',p,'Criar a fundação do frontend React JS','Dispor de navegação e layout reutilizáveis.','Montar rotas, shell, estilos e cliente de API.','Implementar menu e componentes comuns aprovados || Configurar tratamento de erro e sessão || Padronizar moeda, datas, unidade e tradução de status','Rotas e estados base funcionam por teclado; seleção do menu corresponde à página.','Evita refazer componentes em cada tela.',deps='devsetup designsystem uxstates apicontract',owner='Frontend')
add('dbfoundation',p,'Criar o esquema inicial e o controle de migrações','Evoluir banco sem ajustes manuais improvisados.','Implementar migrações base, usuários técnicos e constraints.','Separar permissões de aplicação e migração || Criar índices e versões iniciais || Validar aplicação e recuperação de migração em base descartável','Banco vazio fica pronto automaticamente; migração falha de modo diagnosticável.','Reduz risco na instalação e atualização local.',deps='storage gofoundation')
add('qualitypipeline',p,'Configurar verificações automáticas do projeto','Detectar regressões antes da entrega.','Criar pipeline de lint, testes, análise de dependências e build.','Executar Go, React e testes contratuais apropriados || Bloquear publicação de artefato com verificações obrigatórias falhas || Separar CI de acesso à máquina de produção','Commit válido produz resultado rastreável; PR não confiável não executa na rede da Majucau.','Reduz falhas e exposição da rede local.',deps='gofoundation reactfoundation',refs='Repositório público; recomendação GitHub Actions',owner='Engenharia + Infraestrutura')
add('observabilitybase',p,'Criar logs e rastreio técnico básicos','Diagnosticar falhas sem expor dados sensíveis.','Padronizar IDs de requisição, erro, lote e operação.','Implementar logs estruturados com mascaramento || Correlacionar API, job, lote e fonte || Definir métricas de latência, falhas e tamanho das filas','Erro visível ao usuário possui referência que encontra diagnóstico técnico sem tokens ou extratos completos.','Facilita suporte e investigação.',deps='gofoundation threatmodel')

p='03 Identidade e configurações'
add('identity',p,'Implementar autenticação e administração inicial','Permitir entrada segura no ambiente local.','Construir login e integração com identidade aprovada.','Criar primeiro administrador sem senha fixa no pacote || Implementar sessão, logout e expiração || Aplicar recuperação e MFA conforme fluxo homologado','Sessão expirada não acessa API; recuperação não permite tomar conta de outro usuário.','Protege a entrada no sistema.',deps='accesspolicy dbfoundation reactfoundation threatmodel',refs='L-26; Y_CEI_Tela_17')
add('authorization',p,'Aplicar permissões no backend e na interface','Garantir que cada perfil faça somente o autorizado.','Implementar matriz de recursos e ações.','Aplicar negação por padrão nas rotas e casos de uso || Restringir consultas, exports e operações internas || Refletir permissões na UI sem depender dela para segurança','Chamada direta proibida é negada; perfil LEITURA não modifica metas, usuários ou parâmetros.','Evita escalada de privilégios.',deps='identity apicontract',refs='M-057,M-058; H_Contrato_Dados!A38:H38')
add('accessaudit',p,'Registrar auditoria de acesso e mudanças','Saber quem executou cada alteração material.','Persistir eventos com ator, alvo, data, resultado e motivo.','Registrar mudanças de perfil, bloqueio, metas e parâmetros || Preservar antes/depois e vínculo com requisição || Restringir acesso à auditoria e aplicar retenção aprovada','Histórico permanece consultável após bloqueio e rollback; nenhum segredo é registrado.','Permite investigar ações e explicar alterações.',deps='authorization observabilitybase',refs='H_Contrato_Dados!A39:H39')
add('usersscreen',p,'Implementar T17 Usuários e o ciclo de vida das contas','Administrar acessos de forma compreensível.','Construir lista, perfis, detalhes e convites aprovados.','Calcular cartões e distribuição com população definida || Implementar convite, ativação, bloqueio e desbloqueio || Revogar sessões quando o bloqueio exigir e proteger o último administrador','Contagens conferem com filtros; bloqueado perde acesso; convite vencido não ativa conta.','Mantém controle centralizado do acesso.',deps='authorization accessaudit uxstates',refs='T17; Y_CEI_Tela_17; T-CEI17-01..08')
add('parameterversions',p,'Implementar registro e vigência dos parâmetros','Reproduzir resultados com a regra vigente em cada data.','Persistir parâmetros tipados, origem e histórico.','Validar tipo, unidade e faixa por parâmetro || Versionar valor, regra, vigência e evidência || Proibir sobreposição de vigências e edição sem permissão','Cálculo histórico recupera versão utilizada; zero válido não é confundido com ausência.','Evita alterações retroativas silenciosas.',deps='storage authorization accessaudit',refs='M-056; H_Contrato_Dados!A34:H35')
add('parametersscreen',p,'Implementar T16 Parâmetros e fluxos autorizados de edição','Mostrar regras vigentes e suas fontes.','Construir central de consulta e edições específicas aprovadas.','Apresentar grupos, valores, origem e estado || Conectar cada parâmetro à regra do domínio || Implementar aprovação, motivo e rollback onde homologados','Sem editor genérico nem valores fictícios; parâmetros sem aprovação não aparecem como vigentes.','Ajuda a Majucau a entender o efeito de cada configuração.',deps='parameterversions designsystem',refs='T16; W_CEI_Tela_16; T-CEI16-01..08')

p='04 Dados e integrações'
add('provenance',p,'Implementar proveniência e snapshots de fatos','Rastrear indicadores até a origem.','Criar metadados e consultas de linhagem.','Persistir origem, IDs, lote, datas, posição e versão || Vincular fatos derivados às entradas || Preservar histórico de correções e versões','Um indicador chega ao registro e à regra que o produziram; reprocessamento preserva versões.','Permite conferir qualquer número relevante.',deps='dataquality dbfoundation accessaudit',refs='M-037; H_Contrato_Dados!A3:H3')
add('jobengine',p,'Implementar execução controlada de trabalhos em segundo plano','Processar integrações sem travar consultas.','Criar agendamento, tentativas e recuperação de jobs.','Persistir estado, checkpoint e tentativa || Impedir execução concorrente duplicada da mesma carga || Aplicar cancelamento, timeout e retomada após reinício','Queda do processo não perde o trabalho nem duplica fatos; limites são configuráveis.','Sustenta sincronização e reprocessamento local.',deps='gofoundation dbfoundation observabilitybase',refs='U_CEI_Tela_15')
add('blingcontract',p,'Validar acesso e cobertura dos dados do Bling','Provar que os campos necessários estão disponíveis.','Fazer descoberta técnica em conta e permissões autorizadas.','Mapear OAuth, escopos, callback e renovação || Verificar produtos, vendas, títulos, estoque, OPs, compras e NF-e || Registrar campos históricos ou endpoints ausentes sem inventá-los','Matriz requisito→campo real inclui limitações de histórico, paginação e volume.','Evita construir telas apoiadas em dados inexistentes.',deps='filecontracts localrequirements threatmodel',refs='Bling documentação oficial; H_Contrato_Dados')
add('blingadapter',p,'Implementar o adaptador de leitura do Bling','Ingerir dados oficiais sem alterar o ERP.','Construir cliente e autenticação no backend.','Armazenar credenciais fora do frontend || Renovar tokens com exclusão de concorrência || Aplicar paginação, limites vigentes, retry e erros de autenticação','Adaptador usa somente operações aprovadas; 401/429/falha de rede geram diagnóstico e retomada segura.','Mantém integração estável e credenciais protegidas.',deps='blingcontract jobengine provenance',refs='M-003,M-035; documentação Bling')
add('fileingestion',p,'Implementar leitura da pasta controlada','Receber arquivos sem destruir evidências.','Criar recepção, staging e identificação de lotes.','Esperar arquivo terminar de ser gravado || Calcular hash e registrar cópia interna conforme política || Validar extensão, tamanho, estrutura e acesso a caminhos','Arquivo parcial ou não autorizado não vira carga; origem permanece conforme política homologada.','Evita importação incompleta e perda do original.',deps='filecontracts jobengine provenance threatmodel',refs='M-009,M-010; L-11,L-12')
add('parsers',p,'Implementar validação e interpretação dos arquivos','Converter entradas heterogêneas em registros confiáveis.','Construir parsers por contrato e versão.','Validar colunas, encoding, separadores, datas, moeda e sinais || Distinguir célula vazia, zero e conteúdo inválido || Registrar rejeições por linha e rejeição total quando o contrato exigir','Amostras válidas produzem registros esperados; arquivo incompatível explica o erro sem produzir números parciais ocultos.','Evita erros silenciosos de importação.',deps='fileingestion',refs='H_Contrato_Dados; T-FILE-*')
add('idempotency',p,'Deduplicar arquivos e fatos de negócio','Garantir que repetir uma carga não altere os totais.','Implementar chaves e transações de importação.','Deduplicar por hash e chave de evento || Preservar eventos diferentes com o mesmo número de transação || Tratar arquivo corrigido como nova versão rastreável','Carga repetida e duas cargas concorrentes não duplicam fatos; estorno legítimo é preservado.','Protege todos os indicadores contra duplicidade.',deps='parsers blingadapter storage',refs='M-038; T-IDEMP-*')
add('salesingest',p,'Ingerir produtos, clientes e vendas realizadas','Criar base oficial de vendas por item e canal.','Mapear entidades Bling e estados da venda.','Preservar IDs por pedido/item/SKU || Tratar cancelamentos, devoluções e alterações || Identificar B2C/B2B com regra aprovada e preservar unidade','Venda Bling é contada uma vez; evento Nuvem não cria outra venda.','Sustenta resultados e projeções sem duplicidade.',deps='idempotency blingcontract',refs='M-003; H_Contrato_Dados!A4:H4')
add('receivableingest',p,'Ingerir recebíveis e eventos do Nuvem Pago','Separar direito a receber de venda e recebimento.','Mapear B2C por arquivos e B2B por Bling.','Persistir agenda, valor bruto/líquido, parcela e evento || Preservar taxas, juros, custos e sinal do extrato || Ligar chargeback/estorno à origem sem apagar o evento inicial','B2C e B2B não duplicam direitos; contrato de taxa não é somado sobre custo já realizado.','Melhora a confiabilidade das contas e da conciliação.',deps='idempotency salesingest',refs='M-004,M-005,M-011,M-012; H_Contrato_Dados!A5:H6')
add('payableingest',p,'Ingerir obrigações e movimentos financeiros','Formar títulos reais e suas evidências de pagamento.','Ler Bling e fontes bancárias aprovadas.','Mapear documento, fornecedor, vencimento, valor e eventos || Preservar datas de competência e caixa separadas || Não transformar recomendação ou forecast em obrigação','Cada título possui chave de origem e histórico; previsão de compra não aparece como dívida constituída.','Evita compromissos financeiros fictícios.',deps='idempotency partial',refs='M-006,M-007; T04')
add('opsingest',p,'Ingerir estoque, produção, compras e notas de entrada','Criar uma posição operacional única.','Mapear snapshots e estados operacionais do Bling.','Ler saldos por SKU/unidade/depósito e mínimo || Mapear OP planejada, em andamento e concluída || Vincular pedido atendido, timestamp e NF-e de entrada','Fatos mantêm IDs, posição e unidade; campo ausente é indisponível e não zero.','Faz Estoque, Produção e Compras concordarem.',deps='idempotency blingcontract',refs='M-035; H_Contrato_Dados!A11:H14,A19:H20')
add('logisticsingest',p,'Ingerir etiquetas, faturas e frete da nota fiscal','Preservar o custo logístico realizado e provisório.','Relacionar Nuvem Envio, envio, pedido e NF de saída.','Mapear cotação e fatura por envio || Substituir cotação somente quando sua fatura chegar || Diferenciar NF válida sem frete de falha na leitura','Fatura e cotação do mesmo envio não se somam; status e origem do custo permanecem visíveis.','Evita duplicar frete e distorcer margens.',deps='idempotency salesingest filecontracts',refs='M-013..M-016; H_Contrato_Dados!A7:H9')
add('supplementaryingest',p,'Ingerir perdas, ajustes e extratos de investimentos','Completar fontes aprovadas sem inventar fatos financeiros.','Construir adaptadores por tipo de arquivo.','Identificar ocorrência de perda e vínculo Bling || Preservar posição e movimentações dos investimentos || Ingerir ajustes e fontes complementares com origem e regra própria','Arquivo de perdas não cria venda, caixa ou movimento de estoque; fontes não configuradas não aparecem como ativas.','Permite compor análises mantendo a separação dos fatos.',deps='parsers idempotency accountingpolicy',refs='M-024..M-029,M-033; T15')
add('freshness',p,'Controlar atualização e falha por fonte','Mostrar claramente quando os dados ficaram antigos.','Implementar política de freshness e snapshots válidos.','Guardar última tentativa e último sucesso separadamente || Calcular STALE conforme prazo de cada fonte || Preservar último snapshot válido com data e aviso','Falha não zera saldos nem atualiza falsamente a data; fonte sem primeira carga fica indisponível.','Evita decisões sobre dados antigos apresentados como atuais.',deps='jobengine provenance filecontracts',refs='L-24; U_CEI_Tela_15')
add('integrationsscreen',p,'Implementar T15 Importações e Integrações','Permitir diagnosticar a entrada de dados.','Construir listagem de fontes, lotes, rejeições e tentativas.','Calcular cartões com período explícito || Mostrar detalhes, hash, aceitações e rejeições sem segredos || Executar reprocessamento autorizado pelo mesmo motor de importação','Reprocessar mantém idempotência; fontes reais e estados conferem com lotes; export depende da decisão por tela.','Reduz tempo para corrigir uma integração.',deps='freshness idempotency authorization reactfoundation actionpolicy',refs='T15; U_CEI_Tela_15; T-CEI15-01..08')

p='05 Tesouraria e conciliação'
add('matchengine',p,'Implementar conciliação por evidência e unicidade','Relacionar venda, transação e recebimento sem falso vínculo.','Construir regras de matching versionadas.','Priorizar ID Bling validado || Homologar fallback nome/valor, normalização, datas e tolerância || Bloquear reutilização e manter ambíguos para análise','Dois candidatos não geram match automático; diferença material preserva divergência.','Evita baixa ou recebimento associados à operação errada.',deps='receivableingest payableingest salesingest parameterversions',refs='M-008; T03/T05',questions='Q-19')
add('manualmatch',p,'Implementar revisão, confirmação e desfazimento de conciliação','Permitir corrigir exceções com trilha de decisão.','Criar fluxo contextual conforme permissões.','Exibir evidências das duas pontas e regra aplicada || Exigir motivo nas decisões manuais aprovadas || Impedir conflito concorrente e registrar reversão sem apagar histórico','Revisão não altera origem Bling indevidamente; desfazer restaura vínculos consistentes.','Resolve casos que não podem ser automatizados.',deps='matchengine accessaudit actionpolicy',refs='L-23; T05/T13')
add('reconciliationscreen',p,'Implementar T05 Conciliação','Dar visibilidade aos vínculos e exceções.','Construir cartões, tabela, distribuição e detalhamento.','Adicionar busca/filtros aprovados e paginação || Exibir ID Bling, origem Nuvem, bruto, recebimento e situação || Conectar pendentes, ambíguos, divergentes, chargebacks e regras','Contagens totalizam a mesma população; cada linha permite consultar evidência e revisão autorizada.','Facilita resolver divergências sem procurar em vários sistemas.',deps='manualmatch reactfoundation',refs='T05; T-RECON-*')
add('receivables',p,'Implementar regras e leitura de Contas a Receber','Mostrar direitos abertos, recebidos e vencidos corretamente.','Calcular saldos e agrupamentos com contratos aprovados.','Separar bruto/líquido, canal, vencimento e liquidação || Tratar parcelas, atraso, antecipação, devolução e chargeback || Definir estados de negócio separados de conciliação','Recebido no mês usa data de liquidação; vencido usa posição e regra temporal; totais não duplicam fontes.','Apoia cobrança e planejamento de caixa.',deps='receivableingest matchengine dataquality',refs='T03; M-004,M-005',questions='Q-20')
add('receivablesscreen',p,'Implementar T03 Contas a Receber','Expor valores e exceções de recebimento de modo rastreável.','Construir cartões, lista, distribuição e meios de pagamento.','Conectar detalhes e alertas aos filtros corretos || Mostrar cliente, origem, vencimento, bruto, líquido e status || Traduzir rótulos técnicos conforme padrão aprovado','Lista, cartões e gráfico usam a mesma posição; usuário chega à origem de qualquer valor.','Reduz dúvidas sobre o que ainda será recebido.',deps='receivables reconciliationscreen',refs='T03')
add('payables',p,'Implementar regras de Contas a Pagar','Mostrar obrigações e efeitos de pagamento de forma única.','Aplicar a decisão C-01 e o calendário de vencimentos.','Calcular aberto, vence hoje, atrasado e próximos sete dias || Tratar valor diferente, estorno e cancelamento conforme regra || Separar divergência de valor de status temporal','Exemplo R$1.000/R$600 reproduz decisão aprovada; título futuro não aparece vencido na data anterior.','Evita saldo a pagar incorreto.',deps='payableingest partial matchengine',refs='T04; C-01')
add('payablesscreen',p,'Implementar T04 Contas a Pagar','Permitir acompanhar fornecedores, vencimentos e divergências.','Construir cartões, obrigações, categorias e detalhamento.','Mostrar documento e vínculo financeiro || Conectar vencidos, impostos, fretes e conciliação || Reconciliar distribuição e total de divergências','Valor de divergências é o mesmo nos componentes com igual filtro; ações obedecem permissões.','Ajuda a priorizar pagamentos e análise.',deps='payables reactfoundation',refs='T04')
add('cashengine',p,'Implementar fluxo de caixa realizado, previsto e projetado','Calcular a trajetória do caixa sem dupla contagem.','Combinar posição bancária e eventos temporais aprovados.','Definir saldo inicial e tratamento de contas/transferências internas || Substituir previsto pela liquidação correspondente || Calcular horizontes diários, mínimos e folga sobre a reserva vigente','Saldo final reconcilia com saldo inicial e movimentos; 30/60 dias respeitam datas e limites aprovados.','Sustenta decisões de liquidez.',deps='receivables payables supplementaryingest dataquality investmentpolicy',refs='T02; M-002; C-02; L-07',questions='Q-21')
add('criticalweek',p,'Implementar seleção e memória da semana crítica','Explicar qual semana foi selecionada e por quê.','Aplicar algoritmo, calendário e posição de caixa aprovados.','Calcular entradas e despesas por semana || Resolver empates e semanas incompletas || Preservar indicadores de mínimo de caixa como medida distinta quando aprovados','Dataset com maior despesa e menor saldo em semanas diferentes produz decisão esperada.','Impede divergência entre fluxo e calculadora.',deps='cashengine investmentpolicy',refs='T02/T08; C-02,L-07')
add('cashscreen',p,'Implementar T02 Fluxo de Caixa','Apresentar a posição e os próximos compromissos.','Construir cartões, gráfico combinado, semana crítica e alertas.','Distinguir realizado, previsto e projetado com legendas || Conectar detalhes, reserva, saldo transferível e períodos || Mostrar posição da fonte e indisponibilidade de cálculos parciais','Valores, folgas, datas e gráfico conferem com motor; export mantém filtros aprovados.','Torna a situação do caixa compreensível.',deps='criticalweek reactfoundation actionpolicy',refs='T02')

p='06 Resultados, perdas e aplicações'
add('historicalcost',p,'Preservar o custo Bling válido para cada venda','Sustentar CMV e margem histórica auditáveis.','Implementar custo por SKU com validade e evidência.','Mapear snapshot histórico confirmado || Vincular custo à data da venda || Aplicar decisão de indisponibilidade quando só houver custo atual','Venda antiga não recebe custo atual como se fosse histórico confirmado; BOM e NF não substituem a metodologia financeira.','Evita margem histórica artificial.',deps='salesingest accountingpolicy provenance',refs='M-019,M-020; L-03')
add('financialmapping',p,'Implementar classificação e competência financeira','Converter fatos em linhas financeiras sem conta genérica.','Persistir mappings aprovados por tipo e versão.','Classificar receita, deduções, custos, perdas, juros, fretes e tributos || Manter UNMAPPED fora do resultado definitivo || Reprocessar versões com trilha e impacto explícito','Cada fato mapeado tem conta/regra/data; desconhecido gera pendência, nunca conta coringa.','Permite conferir a composição do resultado.',deps='accountingpolicy parameterversions provenance',refs='M-017,M-018,M-029; H_Contrato_Dados!A18:H18')
add('losses',p,'Implementar perdas e recuperações sem dupla contagem','Reconhecer eventos uma única vez no período correto.','Relacionar planilha, origem oficial e decisão financeira.','Separar ocorrência, confirmação, baixa e recuperação || Vincular eventos equivalentes entre arquivos e Bling || Propagar competência e estado de reconhecimento aprovados','Aprovação de ressarcimento não altera caixa sem recebimento; mesma perda não reduz DRE duas vezes.','Protege resultado e rastreabilidade das perdas.',deps='supplementaryingest financialmapping',refs='M-024..M-026; L-04,L-14')
add('dreengine',p,'Implementar o motor da DRE Majucau','Calcular linhas e subtotais por competência.','Construir demonstração com cobertura e memória.','Aplicar receita, deduções, CMV/CPV, despesas, perdas, financeiro e tributos || Propagar ausência de fonte e pendências de mapping || Versionar cálculo e permitir detalhe por origem','Subtotais reconciliam; linha obrigatória ausente não vira zero nem desaparece; resultado incompleto não fica confirmado.','Oferece resultado verificável.',deps='historicalcost financialmapping losses',refs='T06; M-017..M-029')
add('drescreen',p,'Implementar T06 DRE','Explicar como o resultado foi formado.','Construir linhas, cartões, composição e navegação.','Mostrar competência, sinais e margem com denominador explícito || Definir a semântica do gráfico sem somar subtotais sobrepostos || Abrir lançamentos, perdas e mapeamentos pendentes','Tabela reproduz motor; percentuais derivam dos valores e base aprovada; gráfico não contradiz o resultado.','Evita interpretação enganosa da rentabilidade.',deps='dreengine reactfoundation designsystem',refs='T06',questions='Q-22')
add('trialbalanceengine',p,'Implementar o motor do balancete','Preservar partidas e saldos auditáveis.','Reconstruir débitos, créditos, contrapartidas e abertura.','Ingerir saldos iniciais da fonte aprovada || Vincular documento e competência às partidas || Registrar diferenças sem criar ajuste automático de fechamento','Débitos e créditos reconciliam quando a base é completa; abertura ausente fica indisponível.','Impede fechamento artificial do balancete.',deps='financialmapping accountingpolicy',refs='T07; M-027,M-028; L-08')
add('trialbalancescreen',p,'Implementar T07 Balancete','Permitir conferir saldos e divergências por conta.','Construir tabela, grupos, cartões e detalhamento.','Exibir saldo inicial, movimentos e saldo final conforme contrato || Explicar natureza devedora/credora e pendências || Ligar contrapartida ao documento original','Saldo não nulo não é divergência por si só; composição usa grupos e base aprovados.','Facilita investigação financeira.',deps='trialbalanceengine reactfoundation',refs='T07',questions='Q-23')
add('investmentledger',p,'Implementar posições e movimentos de aplicações','Unir extratos, transferências e rendimentos sem duplicidade.','Modelar investimentos e vínculo com o Bling.','Separar aporte, resgate, rendimento, transferência e saldo de posição || Reconciliar CDI Plus e período de elegibilidade || Identificar extrato antigo e aplicação sem fonte','Posição não é confundida com aporte acumulado; transferência interna não vira receita ou despesa operacional.','Dá base correta à calculadora e à consulta de aplicações.',deps='supplementaryingest investmentpolicy financialmapping',refs='M-030..M-034; T08',questions='Q-10')
add('investmentcalculator',p,'Implementar o cálculo de capacidade de aplicação','Reproduzir a decisão financeira homologada.','Calcular lucro elegível, reserva, máximo e executável.','Aplicar fonte e corte temporal aprovados || Usar caixa da semana crítica e saldo transferível corretos || Propagar bloqueio por dados ausentes, divergentes ou critérios abertos','Memória reproduz entradas e limites; nenhuma transferência ou aplicação é executada.','Evita valor disponível aparente sem sustentação.',deps='investmentledger criticalweek dreengine investmentpolicy',refs='T08; M-034; C-02,C-03,L-07')
add('calculatorscreen',p,'Implementar T08 Calculadora de Aplicação','Mostrar cálculo, condições e motivos de bloqueio.','Construir indicadores e memória detalhada.','Exibir fonte, período, fórmula e valores intermediários || Distinguir máximo calculado de executável || Conectar parâmetros, DRE, fluxo e aplicações sem ação financeira','Estado OPEN não apresenta capacidade confirmada; tela não exporta nem executa dinheiro conforme contrato a validar.','Torna o resultado compreensível e auditável.',deps='investmentcalculator reactfoundation actionpolicy',refs='T08; T16 regra Tela 08 não exporta')
add('applicationsscreen',p,'Implementar a consulta de Aplicações','Cobrir o módulo citado no menu e na calculadora.','Construir a tela e o detalhamento após completar a especificação.','Homologar campos, filtros e extratos sem mockup recebido || Mostrar histórico de aporte, resgate, rendimento e posição || Reconciliar vínculos com calculadora e Bling','Layout aprovado e totais por período conferem com extratos; ações externas não são inventadas.','Evita entregar um menu sem funcionalidade.',deps='missing investmentledger designsystem',refs='Menus; T08 Ver aplicações',questions='Q-02')
add('pricing',p,'Implementar análise de preço e margem no local aprovado','Cobrir Pricing citado na matriz sem alterar o ERP.','Construir cálculo analítico por SKU e canal.','Homologar rateio de tarifa fixa e parâmetros de margem || Aplicar custo válido, taxas e impostos aprovados || Exibir fórmula e bloquear denominador inválido','Pedido com vários SKUs usa rateio explícito; sugestão não grava preço no Bling.','Permite analisar preço com regra rastreável.',deps='missing historicalcost financialmapping parameterversions',refs='M-021..M-023; L-06,L-10',questions='L-06,L-10')
add('logisticsanalysis',p,'Implementar indicadores de logística no local aprovado','Cobrir os custos e subsídios de frete citados na matriz.','Calcular resultado do frete por pedido e transportadora.','Aplicar custo confirmado/provisório e frete da NF || Calcular subsídio e resultado preservando sinal || Apresentar agregados comparáveis sem afirmar melhor transportadora só pela média','Fatura substitui cotação por envio; origem e qualidade acompanham o indicador.','Evita análise logística baseada em custo duplicado.',deps='missing logisticsingest financialmapping',refs='M-013..M-016; L-16',questions='L-16')

p='07 Estoque, produção e compras'
add('inventoryrules',p,'Implementar classificação e posição de estoque','Mostrar quantidade por item e unidade correta.','Aplicar saldo, tipo, mínimo e pedido aberto aplicável.','Separar produto pronto e insumo || Aplicar igualdade ao mínimo conforme regra aprovada || Calcular abaixo do mínimo sem pedido e com reposição','Produtos prontos não recebem mínimo/alerta de insumo; kg e unidades não são somados.','Evita indicação incorreta de necessidade de compra.',deps='opsingest opsrules dataquality',refs='T09; Q_CEI_Tela_11')
add('inventoryscreen',p,'Implementar T09 Estoque','Exibir a posição operacional informativa.','Construir filtros, lista, cartões e distribuição.','Mostrar pedido, quantidade, mínimo e situação || Calcular distribuição por população de SKUs definida || Conectar lista completa e origem Bling','Contagens reconciliam com Compras; não há escrita de estoque no Bling.','Permite identificar insumos que exigem atenção.',deps='inventoryrules reactfoundation',refs='T09')
add('productiontargets',p,'Implementar metas de produção por SKU e período','Guardar o planejamento interno da Majucau.','Criar cadastro específico de metas versionadas.','Validar unidade, período e SKU || Registrar autor, valor anterior, vigência e motivo || Definir relação ou independência com cenário META da T12','Alteração autorizada mantém histórico; meta ausente é diferente de zero.','Permite comparar produção real e objetivo sem alterar OP.',deps='opsrules parameterversions accessaudit',refs='T10; T16 Meta por SKU',questions='Q-08,Q-12')
add('productionrules',p,'Implementar indicadores de produção realizada','Separar ordens, quantidades e alcance de metas.','Calcular planejado, andamento, concluído e percentual por SKU.','Contar ordens por ID sem confundir com número de SKUs || Usar concluído/meta quando denominador válido || Aplicar classificação homologada durante e após o período','Mesmo dataset produz tabela e cartões consistentes; meta atingida e sem meta são estados inequívocos.','Evita indicadores contraditórios como os do mockup.',deps='opsingest productiontargets opsrules',refs='T10; T10 duplicata')
add('productionscreen',p,'Implementar T10 Produção','Apresentar acompanhamento e acesso às metas.','Construir período, busca, filtros, tabela e cartões.','Exibir unidade e posição de sincronização || Conectar Definir metas ao fluxo autorizado || Preservar natureza informativa e ausência de exportação/alertas conforme regra aprovada','Tabela e distribuição usam a mesma população; nenhuma OP é criada, cancelada ou editada no Bling.','Ajuda a acompanhar produção com confiança.',deps='productionrules reactfoundation',refs='T10; M-052')
add('purchaseeligibility',p,'Implementar elegibilidade de Compras Recomendadas','Usar uma regra única entre Estoque e Compras.','Selecionar insumos no mínimo ou abaixo, sem pedido aplicável.','Reutilizar snapshot e regra de estoque || Excluir pedidos abertos aplicáveis e tratar cancelados/atendidos || Aplicar mesma regra ao cacau independentemente do sinal externo','Contagem coincide com T09 na mesma posição; recomendação não cria pedido nem obrigação.','Evita compras duplicadas e números distintos entre telas.',deps='inventoryrules opsrules',refs='M-042; Q_CEI_Tela_11')
add('purchasehistory',p,'Implementar preço faturado e prazo histórico de compras','Mostrar fatos de compra comprováveis por insumo.','Calcular último preço e tempo até ATENDIDO.','Vincular última NF-e válida ao pedido atendido || Preservar preço, moeda, unidade e quantidade || Usar timestamp real de atendimento com janela/estatística homologadas','Preço não vem de cotação; prazo não usa média genérica de fornecedor sem a regra individual.','Melhora a base de priorização e previsão de compra.',deps='opsingest opsrules',refs='M-043; H_Contrato_Dados!A19:H20')
add('purchasesizing',p,'Implementar quantidade, prioridade e custo de compra','Aplicar o planejamento de compra homologado.','Construir recomendação reproduzível por insumo.','Usar janela histórica, mínimos/múltiplos e fórmula aprovados || Aplicar faixas de prioridade e prazo individual || Tratar ausência de taxa/custo de carregamento como dado insuficiente','Não inventa quantidade ou prioridade quando regra falta; cálculo exibe entradas e versão.','Evita excesso ou fragmentação de compras.',deps='purchaseeligibility purchasehistory opsrules',refs='L-15,L-17,L-18; Q_CEI_Tela_11',questions='L-15')
add('cocoasignals',p,'Implementar sinais externos do cacau','Apresentar risco e oportunidade com fontes verificáveis.','Construir adaptadores e avaliação de sinais homologados.','Ingerir fontes com origem, unidade, data e validade || Aplicar conversões e thresholds versionados || Restringir clima às origens cadastradas e separar elegibilidade operacional','Sinal antigo fica STALE; oportunidade compara preços equivalentes; nenhum sinal gera pedido.','Apoia análise de suprimento sem automatizar compra indevida.',deps='cocoapolicy jobengine parameterversions purchasehistory',refs='M-044; Q_CEI_Tela_11')
add('purchasesscreen',p,'Implementar T11 Compras e exportação de recomendações','Entregar o módulo de compras especificado na planilha.','Construir lista e bloco do cacau no mockup a fornecer.','Apresentar quantidades, preço faturado, prazo e prioridade || Exportar somente lista completa de recomendações no contexto aprovado || Separar ações informativas de pedidos reais no Bling','Não há Gerar pedidos; exportação e cartões reconciliam com a mesma base e versão.','Permite discutir compras com evidência sem alterar o ERP.',deps='missing purchasesizing cocoasignals reactfoundation',refs='Q_CEI_Tela_11; T-CEI11-01..12')

p='08 Projeções e cenários'
add('forecasthistory',p,'Preparar histórico de vendas por SKU para projeções','Construir séries temporais confiáveis.','Consolidar 24 meses com cobertura e qualidade explícitas.','Buscar histórico em janelas compatíveis com API || Tratar cancelamentos, devoluções, períodos sem venda e lacunas || Definir SKU novo, descontinuado e mudanças de unidade','Mês sem fonte não vira venda zero; calendário e cortes temporais são reproduzíveis.','Evita treinar projeções sobre histórico incompleto.',deps='salesingest forecastpolicy analyticschoice',refs='R_CEI_Tela_12')
add('forecastcalendar',p,'Implementar calendário sazonal versionado','Representar eventos relevantes do negócio de chocolates.','Persistir eventos, períodos e versões por ano.','Cadastrar Páscoa, Natal e demais eventos aprovados || Usar datas corretas de eventos móveis || Separar dados conhecidos na data de cada simulação','Modelo registra calendário utilizado e reproduz projeção sem informação futura indevida.','Melhora a interpretação da sazonalidade.',deps='forecastpolicy parameterversions',refs='H_Contrato_Dados!A23:H23; T12')
add('forecastmodel',p,'Construir e comparar modelos de projeção','Selecionar método pelo desempenho observado.','Implementar referência simples e candidatos pertinentes.','Comparar baseline sazonal e métodos adequados ao volume || Manter divisão temporal e parâmetros versionados || Medir tempo/memória em hardware local','Método escolhido tem resultado comparativo reproduzível e atende restrições locais.','Evita complexidade sem ganho demonstrado.',deps='forecasthistory forecastcalendar analyticschoice',refs='M-046; R_CEI_Tela_12')
add('forecastvalidation',p,'Validar WAPE, Bias e MASE sem vazamento temporal','Medir qualidade real e condições de utilização.','Executar backtest e diagnósticos por período e SKU.','Definir fórmulas, sinal do Bias e baseline MASE || Tratar denominadores zero e histórico insuficiente || Avaliar sazonalidades separadas conforme volume e thresholds aprovados','Métricas vêm de execução real; versão não vira CONFIRMED sem critérios atendidos.','Evita confiança em percentuais copiados do mockup.',deps='forecastmodel forecastpolicy',refs='L-20; T-CEI12-01,02,10')
add('targetscenario',p,'Implementar cenários ESTUDO e META','Preservar estudo e planejamento como versões distintas.','Salvar metas em dinheiro, por SKU e mistas.','Distribuir por mix e preço aprovados || Aplicar overrides preservando zero válido || Conciliar orçamento total com arredondamentos e metas específicas','Versão registra autor, modelo base, preço/mix e exceções; mesma versão reproduz quantidades e faturamento.','Evita metas que não fecham com o detalhe.',deps='forecastvalidation forecastpolicy productiontargets',refs='M-048; L-21; R_CEI_Tela_12')
add('productionprojection',p,'Implementar produção projetada a partir das vendas','Calcular necessidade futura pela regra aprovada.','Derivar produção por SKU, cenário e período.','Aplicar regra sem descontar estoque pronto atual conforme contrato candidato || Separar perdas/rendimento somente se homologados || Preservar origem da venda e versão de cenário','Mudança de estoque atual não reduz produção quando mantida essa regra; quantidades não são OPs reais.','Mantém o planejamento coerente com a decisão operacional.',deps='targetscenario forecastpolicy',refs='M-047; R_CEI_Tela_12',questions='Q-11')
add('inventoryprojection',p,'Implementar evolução do estoque projetado','Mostrar trajetória de saldo por cenário.','Acumular posição inicial, produção e vendas.','Usar saldo Bling inicial validado || Calcular saldo por período com a mesma unidade || Evidenciar saldo inicial ausente e quantidades negativas conforme regra','Saldo final=saldo inicial+produção−venda; cada mês começa no saldo anterior.','Explica o impacto das metas no estoque.',deps='productionprojection opsingest',refs='M-047; H_Contrato_Dados!A28:H28')
add('inputprojection',p,'Implementar necessidade de insumos e OP Projetada','Cobrir a aba de insumos para um ano.','Converter produção em insumos com composição aprovada.','Validar fonte, versão e vigência de BOM/ficha técnica || Converter unidades e rendimento/perda conforme regra || Marcar OP Projetada e necessidades como planejamento informativo','Composição ausente bloqueia o SKU afetado; projeção não altera estoque, compras ou OP no Bling.','Evita entregar uma aba de planejamento sem base técnica.',deps='productionprojection opsingest forecastpolicy',refs='H_Contrato_Dados!A12:H12; R_CEI_Tela_12',questions='Q-24')
add('projectionfinancial',p,'Implementar resumo financeiro dos cenários','Relacionar quantidades projetadas a preços e valores.','Calcular faturamento e componentes aprovados por cenário.','Aplicar preço de referência versionado || Distinguir valores projetados dos demonstrativos realizados || Expor bases ausentes e contexto de filtros','Resumo reconcilia com SKUs; não cria receita, caixa ou obrigação financeira realizada.','Permite comparar cenários sem misturar planejamento e resultado.',deps='targetscenario inventoryprojection financialmapping',refs='T12 aba Resumo financeiro; R_CEI_Tela_12',questions='Q-25')
add('projectionsscreen',p,'Implementar T12 Projeções e ajuste de metas','Oferecer estudo e planejamento em uma interface completa.','Construir gráfico, cenário, filtros e quatro abas.','Mostrar métricas reais, ano e versão || Implementar edição por SKU e em lote com validação || Exibir comparação estudo/meta e indisponibilidade dos componentes','Todas as abas funcionam; cartões conferem com contexto total ou subtotal explicitamente indicado.','Permite testar metas entendendo suas consequências.',deps='forecastvalidation targetscenario inventoryprojection inputprojection projectionfinancial reactfoundation',refs='T12; R_CEI_Tela_12')
add('projectionexport',p,'Exportar o cenário de projeções para Excel','Produzir artefato de planejamento reproduzível.','Gerar XLSX estruturado do snapshot selecionado.','Criar Resumo_Cenario, Projecao_Vendas_SKU, Projecao_Producao_SKU e Estoque_Projetado_SKU || Incluir Metas, Qualidade_Estudo, OP_Projetada e Metadados || Preservar filtros, versões, unidades e marcação PROJECTED','Valores conciliam com tela; OP é explicitamente projetada e nenhum fato é escrito no Bling.','Permite discutir planejamento fora do sistema com contexto.',deps='projectionsscreen authorization',refs='M-049; R_CEI_Tela_12; T-CEI12-11..13')

p='09 Controle e visão executiva'
add('pendingengine',p,'Implementar registro único de pendências','Concentrar problemas sem duplicar suas regras.','Criar ocorrências e vínculos aos módulos de origem.','Modelar estados, responsável, dependência e evidência || Deduplicar pela condição e origem || Registrar resolução somente pelo fluxo autorizado do tipo','Um evento mantém um pending_id rastreável; visualizar não fecha a pendência.','Evita problemas ocultos ou duplicados.',deps='provenance actionpolicy accessaudit',refs='M-051,M-054; S_CEI_Tela_13')
add('pendingscreen',p,'Implementar T13 Lançamentos e Pendências','Permitir localizar e resolver exceções.','Construir filtros, lista, distribuição e ações contextuais.','Definir contagens exclusivas ou sobrepostas com rótulo explícito || Abrir origem e fluxo de resolução correto || Exibir dependência de regra/dado e responsável','Total não repete o erro 53 versus soma 58 do mockup; estado não muda sem evidência.','Facilita tratamento diário das exceções.',deps='pendingengine reactfoundation authorization',refs='T13; S_CEI_Tela_13')
add('alertengine',p,'Implementar eventos de alerta com regra única de origem','Chamar atenção para condições reais.','Publicar alertas a partir dos módulos responsáveis.','Definir identidade, prioridade, posição e ciclo de vida || Deduplicar e preservar histórico de resolução/recorrência || Não criar thresholds próprios na central ou alertas T10 por inferência','Mesmo fato liga alert_id, pending_id e origem; nenhuma central recalcula regra divergente.','Evita ruído e falsos alertas.',deps='pendingengine freshness inventoryrules cashengine actionpolicy',refs='M-052,M-054; T_CEI_Tela_14')
add('alertsscreen',p,'Implementar T14 Alertas','Consolidar o que exige atenção.','Construir prioridades, módulos, filtros e detalhes.','Separar ativos e resolvidos no período || Reconciliar distribuição com mesma população || Conectar alerta ao módulo de origem e à pendência associada','Cartões não usam população diferente sem explicar; resolução mantém histórico e responsabilidade.','Permite priorizar problemas reais.',deps='alertengine reactfoundation',refs='T14; T_CEI_Tela_14')
add('executivescreen',p,'Implementar T01 Visão Executiva','Consolidar indicadores aprovados para gestão.','Construir a tela após receber e fechar a especificação.','Definir indicadores, fontes, períodos e navegação || Reutilizar resultados dos motores de domínio || Propagar atraso, parcialidade e indisponibilidade de fonte','Cada indicador chega ao módulo e ao detalhe; nenhuma fórmula paralela na dashboard.','Oferece uma visão geral confiável.',deps='missing cashscreen drescreen inventoryscreen productionscreen projectionsscreen alertsscreen',refs='Menus: Visão Executiva',questions='Q-02')
add('extrascreens',p,'Implementar os módulos adicionais confirmados no escopo','Cobrir todos os itens que a Majucau mantiver para a primeira versão.','Detalhar e executar Produtos, Simuladores e Relatórios após decisão.','Fechar o comportamento de cada item sem imagem || Decompor esta tarefa em tarefas por fluxo aprovado || Integrar navegação, permissões e critérios de aceite próprios','Nenhum módulo confirmado permanece apenas como link; exclusão exige decisão registrada.','Evita falsa completude do produto.',deps='missing designsystem domainmap',refs='Menus T12/T13; matriz Pricing/Logística',questions='Q-02',owner='Produto + Full Stack')

p='10 Verificação integrada'
add('tracecoverage',p,'Rastrear cada requisito até tarefa e teste','Garantir cobertura do material de ponta a ponta.','Relacionar regras da matriz e CEIs às entregas.','Mapear M-001..M-058, C-01..03, L-01..26 e testes I_Testes || Complementar contratos incompletos de caixa, metas e investimentos || Marcar regras sem evidência de aceite e corrigir lacunas','Toda regra do escopo tem responsável, implementação prevista e validação específica.','Evita perder requisitos espalhados na planilha.',deps='domainmap apicontract',refs='A_Matriz_Mestra; H_Contrato_Dados; I_Testes',owner='QA + Arquitetura',kind='Qualidade')
add('domainverification',p,'Validar regras de domínio e casos de fronteira','Provar os cálculos fora da interface.','Executar testes unitários e de invariantes relevantes.','Testar centavos, arredondamento, zero/ausente, datas e estados || Validar conflitos resolvidos com exemplos homologados || Cobrir idempotência, estornos e real versus projetado','Falhas materiais são corrigidas; números de mockup não servem como oráculo quando inconsistentes.','Detecta erros de cálculo antes da operação.',deps='tracecoverage investmentcalculator trialbalanceengine purchasesizing inventoryprojection',refs='I_Testes: catálogo previsto, ainda não executado',owner='QA + Backend',kind='Qualidade')
add('integrationverification',p,'Validar integrações, concorrência e reinício','Provar comportamento sob falhas reais de sistema.','Testar banco, arquivos, adaptadores e jobs em ambiente controlado.','Simular 401,429,timeout, arquivo corrompido e versão nova || Repetir carga e interromper processo durante processamento || Disputar reprocessamento e mudança manual concorrente','Último snapshot válido sobrevive; fatos não duplicam; retomada possui evidência.','Reduz falhas de sincronização em produção.',deps='integrationsscreen idempotency blingadapter manualmatch',owner='QA + Integrações',kind='Qualidade')
add('uiverification',p,'Validar fidelidade visual e acessibilidade','Conferir a experiência completa nos dispositivos previstos.','Comparar telas implementadas e decisões UX aprovadas.','Verificar cabeçalhos, menus, layout, tamanhos e conteúdo || Testar teclado, foco, zoom, estados e permissões || Conferir tabelas, porcentagens e gráficos em conjuntos controlados','Todas as telas do escopo passam pelos critérios acordados; alterações de estrutura têm decisão registrada.','Evita entregar apenas uma aparência semelhante sem usabilidade.',deps='executivescreen extrascreens applicationsscreen pricingscreen_placeholder',refs='Todas as imagens e decisões UX',owner='UX + QA',kind='Qualidade')
# Pricing é uma entrega completa; o alias evita um segundo módulo fictício.
tasks[-1]['deps']=['executivescreen','extrascreens','applicationsscreen','pricing','logisticsanalysis','purchasesscreen','parametersscreen','usersscreen']
add('exportverification',p,'Validar arquivos exportados e proteção do conteúdo','Garantir que relatórios correspondam à tela e ao perfil.','Conferir contratos XLSX/CSV/PDF apenas onde aprovados.','Validar colunas, tipos, filtros, totais e metadados || Proteger células de texto contra injeção de fórmulas || Abrir amostras no programa usado pela Majucau','Exports não incluem segredos nem linhas sem permissão; dados conferem com snapshot.','Evita relatório incorreto ou exposição de informação.',deps='projectionexport purchasesscreen actionpolicy',owner='QA',kind='Qualidade')
add('e2everification',p,'Executar jornadas completas de ponta a ponta','Provar que os módulos trabalham juntos.','Testar entradas reais controladas até resultados e resolução.','Percorrer importação→conciliação→contas→caixa→DRE/balancete→calculadora || Percorrer estoque→compras e vendas→estudo→meta→produção/estoque→export || Percorrer erro de fonte→T15→T13/T14→reprocessamento e login→bloqueio','Jornadas conferem IDs, valores, permissões, estados e histórico, com evidência reproduzível.','Demonstra funcionamento do produto completo.',deps='domainverification integrationverification uiverification exportverification',owner='QA + Majucau',kind='Qualidade')
add('securityverification',p,'Validar controles de segurança antes da produção','Verificar que restrições resistem a acesso indevido.','Executar testes direcionados do modelo de ameaças.','Testar bypass de API, troca de perfil, sessão revogada e recuperação || Revisar uploads, exportações, path traversal e exposição de logs || Verificar dependências e segredos no pacote/artefatos','Nenhuma falha crítica sem tratamento; perfil somente leitura não consegue mutar via chamada direta.','Reduz risco de comprometimento de dados.',deps='usersscreen parametersscreen integrationsscreen threatmodel',owner='Segurança + QA',kind='Qualidade')
add('performanceverification',p,'Validar desempenho no hardware local','Demonstrar capacidade de uso e processamento.','Medir jornadas com volume e concorrência esperados.','Medir percentis de resposta, importação, forecast, CPU, memória e disco || Validar carga simultânea sem congelar consultas || Otimizar índices e consultas somente nos gargalos medidos','Metas aprovadas de tempo e capacidade são atingidas; limites conhecidos ficam documentados.','Evita lentidão percebida após a instalação.',deps='e2everification localrequirements analyticschoice',owner='Engenharia + Infraestrutura',kind='Qualidade')
add('businessacceptance',p,'Homologar todos os módulos com a Majucau','Confirmar que o produto atende às regras e ao uso diário.','Executar roteiro com dados e cenários reconhecidos pelos responsáveis.','Conferir amostras com fontes oficiais e responsáveis do negócio || Resolver discrepâncias e repetir apenas verificações afetadas || Registrar aceite de cada módulo e de cada conflito encerrado','Todos os módulos confirmados têm aceite; não se substitui pendência crítica por zero ou tela vazia.','Evita lançar um sistema tecnicamente ativo, mas incorreto para a operação.',deps='e2everification securityverification performanceverification',owner='Majucau + QA',kind='Qualidade')

p='11 Instalação, produção e sustentação'
add('localdesign',p,'Definir a topologia final da instalação local','Tornar operação, acesso e recuperação viáveis.','Desenhar aplicação, banco, arquivos e rede no equipamento escolhido.','Escolher serviço nativo ou containers conforme SO e suporte || Definir acesso local/remoto com autenticação e transporte seguro || Registrar dependência de internet para Bling e sinais externos','Diagrama explica portas, permissões, dados persistentes, operador e comportamento sem internet.','Evita exposição acidental e dependência não planejada.',deps='localrequirements hexagonal threatmodel analyticschoice',owner='Infraestrutura')
add('localhostprep',p,'Preparar o servidor e a rede local','Disponibilizar um ambiente estável para instalação.','Configurar sistema, contas técnicas, armazenamento e acesso.','Aplicar atualizações e permissões mínimas || Configurar DNS/TLS/firewall e acesso remoto aprovado || Validar energia, espaço e reinício automático conforme necessidade','Serviços não executam com privilégio excessivo; somente acessos planejados alcançam a aplicação.','Reduz paradas e riscos da máquina local.',deps='localdesign',owner='Infraestrutura')
add('releasepackage',p,'Gerar pacote versionado de instalação','Entregar uma versão reproduzível e identificável.','Empacotar Go, build React, migrações e dependências aprovadas.','Gerar artefato em CI confiável || Registrar versão, hash e inventário de dependências || Incluir configuração exemplo e instruções sem credenciais','Pacote instala em ambiente limpo; versão visível corresponde ao artefato validado.','Facilita suporte e retorno à versão anterior.',deps='qualitypipeline localdesign',owner='Engenharia + Infraestrutura')
add('staginglocal',p,'Instalar ambiente local de homologação','Ensaiar instalação e atualização sem usar produção.','Criar ambiente e dados separados no hardware previsto ou equivalente.','Instalar pacote e executar migrações || Configurar fontes de teste e credenciais separadas quando disponíveis || Verificar que nenhum job de teste altera a operação real','Ambiente reproduz instalação documentada e permite validar desempenho e restauração.','Reduz surpresas na entrada em produção.',deps='localhostprep releasepackage',owner='Infraestrutura')
add('backupdesign',p,'Configurar backup de banco, arquivos e configuração','Preservar tudo que é necessário para recuperar o serviço.','Implantar cópias automáticas conforme perda tolerável de dados.','Incluir banco, fontes importadas, versões e configurações críticas || Guardar cópia separada do disco e da máquina de produção || Definir retenção, proteção das cópias e verificação de falha','Rotina gera evidência de backup completo e alerta quando falha; cópia no mesmo disco não é a única proteção.','Permite recuperar o sistema após falha do equipamento.',deps='localrequirements staginglocal storage',owner='Infraestrutura')
add('restoreexercise',p,'Testar restauração e recuperação do ambiente','Provar que o backup funciona no prazo necessário.','Restaurar em instalação separada e conferir dados.','Simular perda de banco/arquivo e indisponibilidade da máquina || Reinstalar versão compatível e restaurar cópias || Conferir totais, arquivos, permissões e jobs antes de reativar integrações','Tempo e perda real medidos atendem os limites aprovados; procedimento é executável pelo responsável.','Evita descobrir backup inválido durante uma falha.',deps='backupdesign releasepackage',owner='Infraestrutura + QA',kind='Qualidade')
add('productionmonitoring',p,'Configurar monitoramento operacional local','Perceber falhas antes que invalidem a operação.','Monitorar serviço, banco, disco, sincronização e backups.','Definir sinais e limites com responsáveis || Separar alerta técnico de alerta de negócio || Validar canal escolhido e alertas de falta de espaço/token expirado/fonte antiga','Falha simulada chega ao responsável pelo canal acordado; diagnóstico identifica ação necessária.','Reduz tempo de indisponibilidade e dados desatualizados.',deps='observabilitybase freshness backupdesign',questions='Q-26',owner='Infraestrutura')
add('initialload',p,'Preparar e reconciliar a carga inicial','Começar a produção com base conhecida e validada.','Planejar corte temporal, importação histórica e snapshots iniciais.','Definir data de corte e ordem das cargas || Importar histórico, aberturas, parâmetros, usuários e metas || Reconciliar amostras e totais com fontes sem criar duplicata','Carga inicial tem cobertura, pendências conhecidas e aceite por domínio; fonte ausente permanece explícita.','Evita lançar sobre dados incompletos sem perceber.',deps='businessacceptance staginglocal idempotency',owner='Dados + Majucau')
add('upgradeplan',p,'Ensaiar atualização e retorno à versão anterior','Controlar mudanças futuras sem perder informação.','Criar roteiro de release, migração e recuperação.','Verificar compatibilidade de esquema e pacote || Fazer backup prévio e definir ponto de retorno || Testar rollback de aplicação e recuperação de dados quando migração não for reversível','Procedimento identifica quando rollback simples é possível e quando requer restauração; sem prometer reversão destrutiva automática.','Reduz risco de atualização local.',deps='releasepackage restoreexercise',owner='Infraestrutura + Engenharia')
add('training',p,'Documentar e treinar a rotina da Majucau','Permitir uso e suporte sem depender de memória da equipe.','Produzir guia por perfil e manual de operação.','Explicar consulta, metas, pendências, importações e dados antigos || Documentar login, recuperação, atualização e backup || Executar exercícios com responsáveis do negócio e da máquina','Usuários executam tarefas críticas; operador sabe diagnosticar falha e acionar recuperação.','Reduz erros e dependência informal.',deps='businessacceptance productionmonitoring upgradeplan',owner='Produto + Infraestrutura + Majucau')
add('readiness',p,'Verificar os critérios de entrada em produção','Confirmar que toda a primeira versão está pronta.','Reunir evidências funcionais, técnicas e operacionais.','Conferir todos os módulos e conflitos do escopo || Validar segurança, carga inicial, desempenho, restauração e responsável || Registrar versão, decisão de entrada e plano de contingência','Nenhum requisito obrigatório permanece sem evidência; Majucau autoriza a entrada da versão concreta.','Evita liberar com módulo faltante ou recuperação não testada.',deps='initialload securityverification restoreexercise upgradeplan training productionmonitoring',owner='Majucau + Liderança técnica',kind='Qualidade')
add('golive',p,'Instalar e ativar a primeira versão em produção local','Colocar a versão homologada em uso real.','Executar o roteiro aprovado no ambiente de produção.','Instalar pacote, configurar segredos e aplicar migrações || Ativar fontes e jobs na sequência planejada || Executar verificações rápidas de acesso, dados, módulos e backup','Versão esperada está acessível aos usuários autorizados e produz dados reconciliados; roteiro de contingência disponível.','Inicia a operação completa da Majucau.',deps='readiness',owner='Infraestrutura + Engenharia',kind='Produção')
add('assistedoperation',p,'Acompanhar os primeiros ciclos reais e encerrar a entrega','Confirmar estabilidade no uso cotidiano.','Observar conciliação, fechamento, projeção e atualização de fontes.','Validar ciclos acordados com o negócio || Registrar e corrigir incidentes com evidência || Transferir responsabilidade operacional e rotina de manutenção','Critérios de estabilização acordados são atendidos; suporte, backups e atualizações têm responsáveis.','Consolida a produção e evita abandono após a instalação.',deps='golive',owner='Majucau + Engenharia + Infraestrutura',kind='Produção')

# Complementos identificados na revisão independente de cobertura.
add('cyclemetrics','06 Resultados, perdas e aplicações','Definir e implementar PMR, PMP, PME e ciclo financeiro','Explicar os indicadores de prazo presentes na calculadora.','Homologar e calcular cada indicador separadamente.','Definir período, fontes, numeradores e denominadores de prazo médio de recebimento, pagamento e estoque || Implementar médias e ciclo conforme regra aprovada, preservando ausência e denominador zero || Exibir memória e função diagnóstica, sem alterar a capacidade de aplicação por inferência','Cada indicador tem fonte e fórmula própria; os 28 e 41 dias da imagem não viram constantes; NCG só entra se confirmado no escopo.','Evita confundir três medidas diferentes ou influenciar indevidamente a calculadora.',deps='receivables payables inventoryrules dreengine',refs='T08 indicadores PMR/PMP/PME e ciclo; B_Intersecoes!A12:I12',questions='Q-27',owner='Financeiro + Backend')
extra=tasks.pop();pos=next(i for i,t in enumerate(tasks) if t['key']=='investmentledger');tasks.insert(pos,extra)
add('approvedexports','10 Verificação integrada','Implementar exportações financeiras e de controle aprovadas','Transformar botões homologados em relatórios completos.','Construir contratos de exportação por tela, endpoint, gerador e integração do botão.','Após decisão, implementar formatos, colunas e contexto de T02–T07 e T13–T15 || Aplicar permissão, filtros, snapshot, limite de carga e metadados || Conferir totais, tipos, tratamento de campos perigosos e erros do download','Cada exportação aprovada produz o conteúdo definido e rastreável; telas sem exportação aprovada não recebem função inventada.','Evita aprovar uma interface com botão de exportação sem implementação.',deps='actionpolicy cashscreen receivablesscreen payablesscreen reconciliationscreen drescreen trialbalancescreen pendingscreen alertsscreen integrationsscreen',refs='T02–T07; T13–T15; L-22',owner='Full Stack')
extra=tasks.pop();pos=next(i for i,t in enumerate(tasks) if t['key']=='tracecoverage');tasks.insert(pos,extra)
for i,t in enumerate(tasks):t['id']=f'BK-{i:03}'

# Substitui chaves de dependência por IDs estáveis após compor o catálogo.
bykey={t['key']:t for t in tasks}
bykey['dreengine']['deps']+=['receivableingest','payableingest','logisticsingest']
bykey['trialbalanceengine']['deps']+=['receivableingest','payableingest','logisticsingest','losses']
bykey['calculatorscreen']['deps']+=['cyclemetrics']
bykey['uiverification']['deps']+=['reconciliationscreen','receivablesscreen','payablesscreen','trialbalancescreen','calculatorscreen','pendingscreen']
bykey['exportverification']['deps']+=['approvedexports']
bykey['performanceverification']['deps']+=['staginglocal']
bykey['matchengine']['accept']='Dois candidatos não geram match automático. Em A Pagar, diferença de valor gera divergência e mantém título sem baixa; R$1.000/R$999,99 segue essa regra. Tolerância exige nova decisão explícita.'
bykey['dreengine']['accept']+=' Taxas, juros, obrigações e fretes aprovados reconciliam com as ingestões correspondentes.'
for t in tasks:
    for d in t['deps']:
        assert d in bykey, (t['key'],d)
    t['dependencies']=[bykey[d]['id'] for d in t['deps']]
    t['status']='Aguarda decisão' if t['kind']=='Planejamento' and t['key'] not in ('inventory','repoaudit','visualaudit') else 'Não iniciada'
    if t['key'] in ('inventory','repoaudit','visualaudit'):
        t['status']='Concluída'
        t['evidence']='MAJUCAU_ANALISE_E_DECISOES_v0.md — inventário e análise; inspeção dos materiais e GitHub nesta sessão.'
    t['progress']=1 if t['status']=='Concluída' and t['evidence'] else 0

# Decisões atuais do usuário substituem as alternativas dos documentos somente
# nos pontos que ele respondeu. Nenhuma precedência global foi presumida.
bykey['baseline']['steps'][0]='Registrar Go, React JS, DDD hexagonal monolítico, única empresa Majucau, três diretores e hospedagem local em Windows.'
bykey['partial']['title']='Detalhar os casos de pagamento divergente após decidir C-01'
bykey['partial']['action']='Formalizar a decisão: valor diferente gera divergência e mantém título sem baixa até análise.'
bykey['partial']['steps'][0]='Registrar decisão já recebida para R$1.000/R$600: divergência e título sem baixa até análise.'
bykey['investmentpolicy']['steps'][0]='Registrar decisões já recebidas: semana de maior total de despesas e lucro da DRE Majucau.'
bykey['investmentpolicy']['questions']='L-07,Q-10,Q-21'
bykey['missing']['steps'][1]='Confirmar Aplicações, Pricing, Logística, Simuladores, Relatórios e Produtos; registrar Balanço Patrimonial excluído por decisão atual.'
bykey['localrequirements']['steps'][0]='Windows já confirmado; levantar CPU, RAM, disco, energia, internet e disponibilidade de funcionamento.'
bykey['localrequirements']['steps'][1]='Três diretores já confirmados; definir acesso na rede local ou remoto e navegadores utilizados.'
bykey['localdesign']['steps'][0]='Escolher serviço Windows ou containers conforme edição, suporte e operação; não pressupor servidor Linux.'
bykey['identity']['steps'].append('Compatibilizar convites e recuperação com as ferramentas locais e o canal aprovado para três diretores.')

seen=set(); active=set()
def visit(key):
    assert key not in active, 'Ciclo de dependência: '+key
    if key in seen:return
    active.add(key)
    for d in bykey[key]['deps']:visit(d)
    active.remove(key);seen.add(key)
for t in tasks:visit(t['key'])

Path('work/backlog.json').write_text(json.dumps(tasks,ensure_ascii=False,indent=2),encoding='utf-8')
print('Tarefas:',len(tasks),'concluídas:',sum(t['progress'] for t in tasks))
