import { useState } from 'react'
import { Tooltip } from './components/Tooltip'
import type { TooltipId } from './tooltips'
import sidebarReference from './assets/images/mocap-sidebar.png'

export type MockupScreenKey = 'executive' | 'cashflow' | 'receivables' | 'payables' | 'conciliation' | 'dre' | 'trial-balance' | 'investment-calculator' | 'inventory' | 'production' | 'purchases' | 'forecast' | 'pending' | 'alerts' | 'integrations'

type MockupIcon = 'home' | 'flow' | 'receivable' | 'payable' | 'reconcile' | 'result' | 'balance' | 'investment' | 'calculator' | 'inventory' | 'production' | 'shopping' | 'control' | 'import' | 'user' | 'wallet' | 'trend' | 'calendar' | 'clock' | 'cart' | 'document' | 'database' | 'warning' | 'chart' | 'building' | 'settings' | 'pie' | 'refresh' | 'export' | 'help' | 'bank' | 'money' | 'target' | 'box' | 'flag' | 'leaf'

const iconPaths: Record<MockupIcon, string> = {
  home: 'M3 11 12 4l9 7 M5 10v10h14V10 M9 20v-6h6', flow: 'M4 7h16 M4 12h10 M4 17h16 M16 9l4 3-4 3', receivable: 'M12 3 15 8h4l-3 4 1 8H7l1-8-3-4h4z M10 12h4', payable: 'M5 3h10l4 4v14H5z M15 3v5h4 M8 12h6 M8 16h4', reconcile: 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0-18 M8 12l3 3 5-6', result: 'M5 3h11l3 3v15H5z M8 10h8 M8 14h8 M8 18h5', balance: 'M4 20h16 M6 20V9h12v11 M4 9l8-5 8 5 M9 13h2 M13 13h2', investment: 'M4 17l4-5 3 3 5-7 M14 8h5v5', calculator: 'M5 3h14v18H5z M8 7h8 M8 12h2 M14 12h2 M8 16h2 M14 16h2', inventory: 'M4 7l8-4 8 4v12l-8 4-8-4z M4 7l8 4 8-4 M12 11v12', production: 'M4 19V8l8-4 8 4v11 M8 19v-5h8v5 M7 10h2 M15 10h2', shopping: 'M3 5h2l2 10h11l3-8H6 M9 20a1 1 0 1 0 0 .01 M17 20a1 1 0 1 0 0 .01', control: 'M5 4h14v16H5z M8 8h8 M8 12h8 M8 16h5', import: 'M4 5h16v14H4z M12 8v8 M9 13l3 3 3-3', user: 'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M5 21a7 7 0 0 1 14 0', wallet: 'M3 7h18v12H3z M7 7V5h10v2 M16 13h3', trend: 'M3 17l6-6 4 4 8-9 M16 6h5v5', calendar: 'M5 4v3 M19 4v3 M4 8h16v12H4z M8 12h3 M13 12h3 M8 16h3', clock: 'M12 7v5l3 2 M12 3a9 9 0 1 0 0 18 9 9 0 0 0-18', cart: 'M3 4h2l2 11h10l3-8H6 M9 19a1 1 0 1 0 0 .01 M17 19a1 1 0 1 0 0 .01', document: 'M6 3h9l4 4v14H6z M15 3v5h4 M9 12h6 M9 16h6', database: 'M4 6c0-2 16-2 16 0v12c0 2-16 2-16 0z M4 6c0 2 16 2 16 0 M4 12c0 2 16 2 16 0', warning: 'M12 3l9 17H3z M12 9v5 M12 17v.01', chart: 'M4 19V5 M4 19h17 M8 16v-4 M12 16V8 M16 16v-6', building: 'M4 20V6l8-3 8 3v14 M9 20v-5h6v5 M8 9h1 M12 9h1 M16 9h1', settings: 'M12 8a4 4 0 1 0 0 8 4 4 0 0 0-8 M4 12h2 M18 12h2 M12 4v2 M12 18v2', pie: 'M12 3a9 9 0 1 0 9 9h-9z M12 3v9h9', refresh: 'M20 11a8 8 0 0 0-14-4L4 9 M4 5v4h4 M4 13a8 8 0 0 0 14 4l2-2 M20 19v-4h-4', export: 'M5 4h9 M14 4v5 M14 4l5 5 M19 9v11H5V9', help: 'M9.5 9a2.5 2.5 0 1 1 4.5 1.5c-1 1-2 1.2-2 3 M12 17v.01 M12 3a9 9 0 1 0 0 18 9 9 0 0 0-18', bank: 'M3 9l9-5 9 5 M5 10v8 M9 10v8 M15 10v8 M19 10v8 M3 21h18', money: 'M4 6h16v12H4z M8 12h8 M7 9h.01 M17 15h.01', target: 'M12 3a9 9 0 1 0 9 9 M12 7a5 5 0 1 0 5 5 M12 11a1 1 0 1 0 1 1', box: 'M4 7l8-4 8 4v12l-8 4-8-4z M4 7l8 4 8-4 M12 11v12', flag: 'M5 21V4 M5 5h11l-2 4 2 4H5', leaf: 'M20 4C10 4 4 10 4 20c8-1 15-6 16-16z M4 20l8-8',
}

function Icon({ icon, className = '' }: { icon: MockupIcon; className?: string }) {
  return <svg className={`mocap-icon ${className}`} viewBox="0 0 24 24" aria-hidden="true"><path d={iconPaths[icon]} fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>
}

type NavItem = { key: MockupScreenKey; label: string; icon: MockupIcon; section?: string; tooltip: TooltipId }
const navItems: NavItem[] = [
  { key: 'executive', label: 'Visão Executiva', icon: 'home', section: 'VISÃO EXECUTIVA', tooltip: 'nav.executive' },
  { key: 'cashflow', label: 'Fluxo de Caixa', icon: 'flow', section: 'TESOURARIA', tooltip: 'nav.treasury' },
  { key: 'receivables', label: 'Contas a Receber', icon: 'receivable', tooltip: 'nav.receivables' },
  { key: 'payables', label: 'Contas a Pagar', icon: 'payable', tooltip: 'nav.payables' },
  { key: 'conciliation', label: 'Conciliação', icon: 'reconcile', tooltip: 'nav.conciliations' },
  { key: 'dre', label: 'DRE', icon: 'result', section: 'RESULTADOS', tooltip: 'nav.result' },
  { key: 'trial-balance', label: 'Balancete', icon: 'balance', tooltip: 'nav.accounting' },
  { key: 'trial-balance', label: 'Balanço Patrimonial', icon: 'building', tooltip: 'nav.accounting' },
  { key: 'investment-calculator', label: 'Aplicações', icon: 'investment', section: 'INVESTIMENTOS', tooltip: 'nav.investments' },
  { key: 'investment-calculator', label: 'Calculadora de Aplicação', icon: 'calculator', tooltip: 'nav.investments' },
  { key: 'inventory', label: 'Estoque', icon: 'inventory', section: 'OPERAÇÃO', tooltip: 'nav.treasury' },
  { key: 'production', label: 'Produção', icon: 'production', tooltip: 'nav.treasury' },
  { key: 'purchases', label: 'Compras', icon: 'shopping', tooltip: 'nav.treasury' },
  { key: 'pending', label: 'Lançamentos & Pendências', icon: 'control', section: 'CONTROLE', tooltip: 'nav.result' },
  { key: 'alerts', label: 'Alertas', icon: 'warning', tooltip: 'management.alerts' },
  { key: 'integrations', label: 'Importações / Integrações', icon: 'import', tooltip: 'nav.integrations' },
  { key: 'integrations', label: 'Parâmetros', icon: 'settings', section: 'CONFIGURAÇÕES', tooltip: 'settings.open' },
  { key: 'integrations', label: 'Usuários', icon: 'user', tooltip: 'settings.open' },
]

export function MockupSidebar({ screen, onNavigate }: { screen: string; onNavigate: (screen: MockupScreenKey) => void }) {
  return <aside className="mocap-sidebar"><div className="mocap-people" style={{ backgroundImage: `url(${sidebarReference})` }} aria-hidden="true" /><nav aria-label="Navegação principal" className="mocap-nav">{navItems.map((item, index) => <span key={`${item.label}-${index}`} className="mocap-nav-wrap">{item.section && <span className="mocap-nav-section">{item.section}</span>}<Tooltip id={item.tooltip}><button type="button" className={`mocap-nav-item ${screen === item.key ? 'active' : ''}`} onClick={() => onNavigate(item.key)} aria-current={screen === item.key ? 'page' : undefined} aria-label={item.label === 'Importações / Integrações' ? 'Integrações' : undefined}><Icon icon={item.icon} /><span>{item.label}</span></button></Tooltip></span>)}</nav></aside>
}

type Card = { label: string; icon: MockupIcon; tone: 'green' | 'blue' | 'orange' | 'red' | 'purple'; supporting?: string; action?: string; variant?: 'minimum-balance' }
type ScreenLayout = 'standard' | 'critical' | 'calculation' | 'market' | 'forecast'
type ScreenConfig = { number: string; title: string; subtitle: string; cards: Card[]; middleTitle: string; middleSubtitle: string; rightTitle: string; rightSubtitle: string; lower: Card[]; alerts: string[]; table?: string[]; chart?: boolean; layout?: ScreenLayout }

const configs: Record<Exclude<MockupScreenKey, 'integrations'>, ScreenConfig> = {
  executive: { number: '01', title: 'VISÃO EXECUTIVA', subtitle: 'Panorama financeiro e operacional do negócio', cards: [{ label: 'SALDO ATUAL', icon: 'bank', tone: 'green', supporting: 'Banco conciliado' }, { label: 'A RECEBER', icon: 'receivable', tone: 'blue', supporting: 'B2C + B2B' }, { label: 'A PAGAR', icon: 'payable', tone: 'orange', supporting: 'Bling' }, { label: 'MENOR SALDO 30 / 60 DIAS', icon: 'trend', tone: 'blue', variant: 'minimum-balance' }], middleTitle: 'FLUXO DE CAIXA PROJETADO', middleSubtitle: 'Próximos 30 dias', rightTitle: 'DISTRIBUIÇÃO DO SALDO', rightSubtitle: 'Por conta / meio', lower: [{ label: 'VENDAS DO MÊS', icon: 'cart', tone: 'blue', supporting: 'Meta' }, { label: 'MARGEM BRUTA', icon: 'chart', tone: 'green', supporting: 'Meta' }, { label: 'ESTOQUE / COBERTURA', icon: 'box', tone: 'orange', supporting: 'Cacau, embalagens e acabados' }, { label: 'PRODUÇÃO PREVISTA', icon: 'production', tone: 'blue', supporting: 'Próximas 2 semanas' }, { label: 'COMPRAS PREVISTAS', icon: 'shopping', tone: 'purple', supporting: 'Próximos 15 dias' }], alerts: ['Saldo projetado abaixo da reserva mínima', 'Obrigações vencidas aguardando fonte Bling', 'Recebimentos em atraso aguardando conciliação', 'Conciliação pendente aguardando fonte oficial'], chart: true },
  cashflow: { number: '02', title: 'FLUXO DE CAIXA', subtitle: 'Realizado, previsto e projetado do caixa', cards: [{ label: 'SALDO ATUAL', icon: 'bank', tone: 'green', supporting: 'Banco conciliado' }, { label: 'ENTRADAS 30 DIAS', icon: 'trend', tone: 'green', supporting: 'Realizado + previsto' }, { label: 'SAÍDAS 30 DIAS', icon: 'trend', tone: 'orange', supporting: 'Compromissos e pagamentos' }, { label: 'MENOR SALDO 30 / 60 DIAS', icon: 'trend', tone: 'blue', variant: 'minimum-balance' }], middleTitle: 'FLUXO DE CAIXA CONSOLIDADO', middleSubtitle: 'Próximos 30 dias', rightTitle: 'SEMANA CRÍTICA', rightSubtitle: 'Maior total de despesas / compromissos', lower: [{ label: 'RECEBIDO NO MÊS', icon: 'cart', tone: 'blue', supporting: 'Até a data-base' }, { label: 'PAGO NO MÊS', icon: 'document', tone: 'red', supporting: 'Até a data-base' }, { label: 'RESERVA MÍNIMA', icon: 'wallet', tone: 'orange', supporting: 'Parametrizada' }, { label: 'SALDO TRANSFERÍVEL', icon: 'flow', tone: 'blue', supporting: 'Aplicação possível' }, { label: 'NÍVEL DE CAIXA', icon: 'chart', tone: 'blue', supporting: 'Acima da reserva' }], alerts: ['Saldo projetado abaixo da reserva mínima', 'Saídas previstas sem categoria', 'Recebimentos em atraso', 'Conciliação pendente'], chart: true, layout: 'critical' },
  receivables: { number: '03', title: 'CONTAS A RECEBER', subtitle: 'Recebíveis, atrasos e conciliação com Nuvem Pago', cards: [{ label: 'TOTAL A RECEBER', icon: 'bank', tone: 'green', supporting: 'Clientes e boletos' }, { label: 'RECEBIDO NO MÊS', icon: 'trend', tone: 'green', supporting: 'Até a data-base' }, { label: 'EM ATRASO', icon: 'clock', tone: 'orange', supporting: 'Recebimentos' }, { label: 'CONCILIAÇÃO', icon: 'refresh', tone: 'blue', supporting: 'Bling × Nuvem Pago' }], middleTitle: 'RECEBÍVEIS', middleSubtitle: 'Títulos em aberto e previstos', rightTitle: 'DISTRIBUIÇÃO DOS RECEBÍVEIS', rightSubtitle: 'Por status', lower: [{ label: 'PIX', icon: 'money', tone: 'blue', supporting: 'Liquidação rápida' }, { label: 'BOLETOS', icon: 'document', tone: 'green', supporting: 'Títulos' }, { label: 'CARTÃO', icon: 'money', tone: 'blue', supporting: 'Nuvem Pago' }, { label: 'AMBÍGUOS', icon: 'warning', tone: 'orange', supporting: 'Não conciliar automaticamente' }, { label: 'CHARGEBACKS', icon: 'refresh', tone: 'purple', supporting: 'Vinculados à origem' }], alerts: ['Recebimentos em atraso', 'Matches ambíguos aguardando análise', 'Transações sem ID Bling', 'Regras de match ativas'], table: ['Cliente', 'Origem', 'Vencimento', 'Valor bruto', 'Valor líquido', 'Status'] },
  payables: { number: '04', title: 'CONTAS A PAGAR', subtitle: 'Obrigações, vencimentos e divergências', cards: [{ label: 'TOTAL A PAGAR', icon: 'document', tone: 'orange', supporting: 'Bling' }, { label: 'VENCE HOJE', icon: 'calendar', tone: 'blue', supporting: 'Contas' }, { label: 'EM ATRASO', icon: 'clock', tone: 'orange', supporting: 'Obrigações' }, { label: 'DIVERGÊNCIAS', icon: 'refresh', tone: 'purple', supporting: 'Diferença ≠ pagamento parcial' }], middleTitle: 'OBRIGAÇÕES', middleSubtitle: 'Títulos a pagar e vencimentos', rightTitle: 'DISTRIBUIÇÃO A PAGAR', rightSubtitle: 'Por status', lower: [{ label: 'FORNECEDORES', icon: 'user', tone: 'blue', supporting: 'Ativos' }, { label: 'FRETES', icon: 'shopping', tone: 'green', supporting: 'Etiquetas e NF' }, { label: 'IMPOSTOS', icon: 'document', tone: 'blue', supporting: 'Competência' }, { label: 'SEM PAGTO PARCIAL', icon: 'warning', tone: 'orange', supporting: 'Regra' }, { label: 'VENCIMENTOS 7 DIAS', icon: 'calendar', tone: 'purple', supporting: 'Prioridade' }], alerts: ['Contas a pagar vencendo hoje', 'Obrigações em atraso', 'Títulos com divergência de valor', 'Pagamentos parciais não permitidos'], table: ['Fornecedor', 'Documento', 'Vencimento', 'Valor', 'Categoria', 'Status'] },
  conciliation: { number: '05', title: 'CONCILIAÇÃO', subtitle: 'Bling × Nuvem Pago e rastreabilidade dos matches', cards: [{ label: 'CONCILIADOS', icon: 'reconcile', tone: 'green', supporting: 'Matches confirmados' }, { label: 'PENDENTES', icon: 'clock', tone: 'orange', supporting: 'Aguardando análise' }, { label: 'AMBÍGUOS', icon: 'warning', tone: 'red', supporting: 'Não conciliar automaticamente' }, { label: 'DIVERGENTES', icon: 'refresh', tone: 'purple', supporting: 'Exigem revisão' }], middleTitle: 'MATCHES BLING × NUVEM', middleSubtitle: 'Venda, transação e recebimento', rightTitle: 'STATUS DOS MATCHES', rightSubtitle: 'Por situação', lower: [{ label: 'PRIORIDADE', icon: 'target', tone: 'green', supporting: 'ID BLING' }, { label: 'FALLBACK', icon: 'settings', tone: 'blue', supporting: 'Nome + Valor' }, { label: 'REUSO BLOQUEADO', icon: 'warning', tone: 'blue', supporting: 'Sem duplicidade' }, { label: 'CHARGEBACKS', icon: 'refresh', tone: 'purple', supporting: 'Vinculados à origem' }, { label: 'SEM ID BLING', icon: 'document', tone: 'orange', supporting: 'Análise manual' }], alerts: ['Matches ambíguos aguardando análise', 'Transações sem ID Bling', 'Divergências de valor ou origem', 'Regra ativa: ID / Nome + Valor'], table: ['Venda Bling', 'Transação Nuvem', 'Cliente', 'Valor bruto', 'Recebimento', 'Status'] },
  dre: { number: '06', title: 'DRE', subtitle: 'Demonstrativo do resultado do exercício', cards: [{ label: 'RECEITA BRUTA', icon: 'chart', tone: 'green', supporting: 'Mês atual' }, { label: 'RECEITA LÍQUIDA', icon: 'trend', tone: 'blue', supporting: 'Após deduções' }, { label: 'LUCRO BRUTO', icon: 'box', tone: 'orange', supporting: 'Margem' }, { label: 'RESULTADO LÍQUIDO', icon: 'database', tone: 'green', supporting: 'DRE Majucau' }], middleTitle: 'DRE CONSOLIDADA', middleSubtitle: 'Competência selecionada', rightTitle: 'COMPOSIÇÃO DO RESULTADO', rightSubtitle: 'Principais blocos', lower: [{ label: 'CMV / CPV', icon: 'box', tone: 'green', supporting: 'Base Bling' }, { label: 'DESPESAS', icon: 'chart', tone: 'green', supporting: 'Operacionais' }, { label: 'PERDAS', icon: 'warning', tone: 'orange', supporting: 'Sem dupla contagem' }, { label: 'TRIBUTOS', icon: 'document', tone: 'blue', supporting: 'Competência' }, { label: 'UNMAPPED', icon: 'document', tone: 'purple', supporting: 'Lançamentos pendentes' }], alerts: ['Lançamentos UNMAPPED na DRE', 'Perdas com competência pendente', 'Resultado financeiro em revisão', 'Sem conta automática de fechamento'], table: ['Descrição', 'Valor (R$)'] },
  'trial-balance': { number: '07', title: 'BALANCETE', subtitle: 'Débitos, créditos e saldos com rastreabilidade', cards: [{ label: 'DÉBITOS', icon: 'bank', tone: 'green', supporting: 'Período' }, { label: 'CRÉDITOS', icon: 'trend', tone: 'blue', supporting: 'Período' }, { label: 'SALDO', icon: 'document', tone: 'orange', supporting: 'Sem conta de ajuste' }, { label: 'DIVERGÊNCIAS', icon: 'warning', tone: 'red', supporting: 'Revisão necessária' }], middleTitle: 'LANÇAMENTOS DO BALANCETE', middleSubtitle: 'Competência selecionada', rightTitle: 'COMPOSIÇÃO DOS SALDOS', rightSubtitle: 'Por grupo contábil', lower: [{ label: 'LANÇAMENTOS', icon: 'cart', tone: 'blue', supporting: 'No período' }, { label: 'CONTRAPARTIDAS', icon: 'chart', tone: 'green', supporting: 'Rastreáveis' }, { label: 'SALDOS INICIAIS', icon: 'box', tone: 'orange', supporting: 'Pendente' }, { label: 'SEM AJUSTE', icon: 'reconcile', tone: 'blue', supporting: 'Sem conta automática' }, { label: 'ORIGEM', icon: 'control', tone: 'purple', supporting: 'Bling + Majucau' }], alerts: ['Divergências de saldo / contrapartida', 'Saldos iniciais permanecem abertos', 'Ausência de saldo inicial não vira zero', 'Sem conta automática para fechar diferença'], table: ['Conta', 'Descrição', 'Débito', 'Crédito', 'Saldo', 'Status'] },
  'investment-calculator': { number: '08', title: 'CALCULADORA DE APLICAÇÃO', subtitle: 'Capacidade de investimento e regras de segurança', cards: [{ label: 'LUCRO ELEGÍVEL', icon: 'chart', tone: 'green', supporting: 'DRE Majucau' }, { label: 'CAIXA CONSOLIDADO', icon: 'bank', tone: 'blue', supporting: 'Posição atual' }, { label: 'RESERVA MÍNIMA', icon: 'wallet', tone: 'orange', supporting: 'Parametrizada' }, { label: 'CAPACIDADE DE APLICAÇÃO', icon: 'trend', tone: 'blue', supporting: 'Saldo transferível' }], middleTitle: 'CÁLCULO DE CAPACIDADE', middleSubtitle: 'Fórmula auditável', rightTitle: 'REGRAS DA DECISÃO', rightSubtitle: 'Critérios vigentes', lower: [{ label: 'CDI PLUS APLICADO', icon: 'chart', tone: 'green', supporting: 'Histórico' }, { label: 'SALDO TRANSFERÍVEL', icon: 'flow', tone: 'blue', supporting: 'Disponível' }, { label: 'SEMANA CRÍTICA', icon: 'clock', tone: 'orange', supporting: 'Diagnóstico' }, { label: 'PMR', icon: 'chart', tone: 'purple', supporting: 'Diagnóstico' }, { label: 'CICLO FINANCEIRO', icon: 'calendar', tone: 'blue', supporting: 'Indicador' }], alerts: ['Posição de caixa da semana crítica permanece aberta', 'Reserva mínima ativa', 'PMR / PMP / PME não alteram automaticamente a aplicação', 'Validação final depende das fontes reais'], table: ['Componente', 'Valor'], layout: 'calculation' },
  inventory: { number: '09', title: 'ESTOQUE', subtitle: 'Estoque realizado, utilizável e cobertura', cards: [{ label: 'ESTOQUE FÍSICO', icon: 'box', tone: 'green', supporting: 'Matérias-primas + acabados' }, { label: 'UTILIZÁVEL', icon: 'chart', tone: 'blue', supporting: 'Descontando reservas e bloqueios' }, { label: 'COBERTURA', icon: 'clock', tone: 'orange', supporting: 'Média atual' }, { label: 'RISCO DE RUPTURA', icon: 'warning', tone: 'red', supporting: 'Abaixo do mínimo' }], middleTitle: 'ESTOQUE POR ITEM', middleSubtitle: 'Saldo, cobertura e validade', rightTitle: 'DISTRIBUIÇÃO DO ESTOQUE', rightSubtitle: 'Por grupo', lower: [{ label: 'SEGURANÇA', icon: 'control', tone: 'blue', supporting: 'Estoque mínimo' }, { label: 'PONTO DE PEDIDO', icon: 'cart', tone: 'green', supporting: 'Monitorados' }, { label: 'ENVELHECENDO', icon: 'clock', tone: 'orange', supporting: 'Atenção' }, { label: 'VALIDADE', icon: 'calendar', tone: 'blue', supporting: 'Próxima' }, { label: 'GIRO', icon: 'chart', tone: 'purple', supporting: 'Últimos 12 meses' }], alerts: ['SKUs abaixo do estoque mínimo', 'Lotes com validade próxima', 'Itens com cobertura inferior a 7 dias', 'Estoque projetado depende do forecast'], table: ['SKU', 'Descrição', 'Físico', 'Reservado', 'Utilizável', 'Cobertura', 'Status'] },
  production: { number: '10', title: 'PRODUÇÃO', subtitle: 'Planejado, em andamento e realizado', cards: [{ label: 'PLANEJADA', icon: 'production', tone: 'blue', supporting: 'Próximas 2 semanas' }, { label: 'EM ANDAMENTO', icon: 'settings', tone: 'green', supporting: 'Lotes liberados' }, { label: 'CONCLUÍDA', icon: 'flag', tone: 'orange', supporting: 'Período atual' } as Card, { label: 'YIELD MÉDIO', icon: 'trend', tone: 'purple', supporting: 'Com perdas controladas' }], middleTitle: 'ORDENS DE PRODUÇÃO', middleSubtitle: 'Planejado x realizado', rightTitle: 'CAPACIDADE E STATUS', rightSubtitle: 'Distribuição das ordens', lower: [{ label: 'CAPACIDADE', icon: 'box', tone: 'blue', supporting: '2 semanas' }, { label: 'LOTES', icon: 'document', tone: 'green', supporting: 'Ativos' }, { label: 'PERDAS', icon: 'warning', tone: 'orange', supporting: 'No período' }, { label: 'RENDIMENTO', icon: 'chart', tone: 'green', supporting: 'Yield médio' }, { label: 'SKU PRODUZIDO', icon: 'box', tone: 'purple', supporting: 'No mês' }], alerts: ['Ordens em atraso', 'Lotes com perda acima do esperado', 'Separar plano realizado e obrigatório', 'BOM versionada impacta a necessidade de insumos'], table: ['Ordem', 'SKU', 'Planejado', 'Em andamento', 'Realizado', 'Status'] },
  purchases: { number: '11', title: 'COMPRAS', subtitle: 'Compras sugeridas, insumos, cacau e fornecedores', cards: [{ label: 'COMPRAS INDICADAS — HOJE', icon: 'shopping', tone: 'purple', supporting: 'Com base na demanda, estoque e lead time' }, { label: 'NECESSIDADE LÍQUIDA TOTAL', icon: 'chart', tone: 'green', supporting: 'Próximos 60 dias' }, { label: 'PEDIDOS CONFIRMADOS', icon: 'document', tone: 'orange', supporting: 'Em trânsito / a receber' }, { label: 'LEAD TIME MÉDIO', icon: 'clock', tone: 'blue', supporting: 'Fornecedores principais' }], middleTitle: 'CACAU — MERCADO E RISCO DE ABASTECIMENTO', middleSubtitle: 'Cotações, clima, safra e câmbio', rightTitle: 'RISCO DE ABASTECIMENTO (CACAU)', rightSubtitle: 'Alto, médio e baixo', lower: [{ label: 'NECESSIDADE DE COMPRA (TONELADAS)', icon: 'chart', tone: 'green', supporting: 'Necessidade líquida' }, { label: 'ORIGEM DA NECESSIDADE', icon: 'leaf', tone: 'green', supporting: 'Produção e estoque' }, { label: 'ALERTAS IMPORTANTES', icon: 'warning', tone: 'orange', supporting: 'Risco climático e cobertura' } as Card], alerts: ['Preço do cacau em queda', 'Risco climático elevado', 'Cobertura de manteiga de cacau inferior a 20 dias', 'Fornecedores com lead time acima da média'], table: ['Insumo', 'Categoria', 'Estoque atual', 'Nec. líquida', 'Qtd. sugerida', 'Preço referência', 'Risco'], layout: 'market' },
  forecast: { number: '12', title: 'PROJEÇÕES', subtitle: 'Forecast, cenários e backtest da demanda', cards: [{ label: 'FORECAST BASE', icon: 'chart', tone: 'green', supporting: 'Próximos 60 dias' }, { label: 'CENÁRIO PESSIMISTA', icon: 'trend', tone: 'red', supporting: 'Variação' }, { label: 'CENÁRIO OTIMISTA', icon: 'trend', tone: 'green', supporting: 'Variação' }, { label: 'WAPE', icon: 'target', tone: 'blue', supporting: 'Acurácia do backtest' }], middleTitle: 'FORECAST x REALIZADO', middleSubtitle: 'Demanda, receita e cenários', rightTitle: 'VERSÃO E BACKTEST', rightSubtitle: 'Metadados da versão ativa', lower: [{ label: 'DEMANDA PREVISTA', icon: 'cart', tone: 'blue', supporting: 'Próximo período' }, { label: 'COBERTURA PROJETADA', icon: 'chart', tone: 'green', supporting: 'Dias' }, { label: 'PRODUÇÃO SUGERIDA', icon: 'box', tone: 'orange', supporting: 'Toneladas' }, { label: 'COMPRA DERIVADA', icon: 'shopping', tone: 'purple', supporting: 'Valor estimado' }, { label: 'SAZONALIDADE', icon: 'trend', tone: 'blue', supporting: 'Páscoa / Natal' }], alerts: ['Forecast preserva a versão original', 'SKUs com backtest acima do limite', 'Promoções afetam a leitura de demanda', 'Ruptura não vira baixa automática'], table: ['SKU', 'Canal', 'Forecast', 'Realizado', 'Desvio', 'Cobertura projetada', 'Status'], chart: true, layout: 'forecast' },
  pending: { number: '13', title: 'LANÇAMENTOS & PENDÊNCIAS', subtitle: 'Exceções, divergências e decisões em aberto', cards: [{ label: 'PENDÊNCIAS ABERTAS', icon: 'warning', tone: 'red', supporting: 'Itens aguardando decisão' }, { label: 'DIVERGÊNCIAS', icon: 'document', tone: 'orange', supporting: 'Registros com divergência' }, { label: 'OPEN / BLOCKED', icon: 'control', tone: 'purple', supporting: 'Itens bloqueados no fluxo' }, { label: 'UNMAPPED', icon: 'import', tone: 'blue', supporting: 'Lançamentos sem mapeamento' }], middleTitle: 'ITENS PENDENTES', middleSubtitle: 'Backlog operacional e financeiro', rightTitle: 'DISTRIBUIÇÃO DAS PENDÊNCIAS', rightSubtitle: 'Por status', lower: [{ label: 'SEMANA CRÍTICA OPEN', icon: 'calendar', tone: 'red', supporting: 'Semana sem definição' }, { label: 'SALDOS INICIAIS OPEN', icon: 'chart', tone: 'green', supporting: 'Contas sem saldo inicial' }, { label: 'PERDAS SEM COMPETÊNCIA', icon: 'document', tone: 'orange', supporting: 'Lançamentos em análise' }, { label: 'TAXA / JUROS NUVEM', icon: 'money', tone: 'blue', supporting: 'Parâmetros pendentes' }, { label: 'MATCH AMBÍGUO', icon: 'refresh', tone: 'purple', supporting: 'Aguardando análise' }], alerts: ['DEV não decide sozinho os itens OPEN/BLOCKED', 'Ausência de dado não vira zero automaticamente', 'Divergência não significa pagamento parcial', 'Regras pendentes permanecem pendentes de decisão'], table: ['Módulo', 'Origem', 'Descrição', 'Status', 'Responsável', 'Ação'] },
  alerts: { number: '14', title: 'ALERTAS', subtitle: 'Central consolidada de exceções e monitoramento', cards: [{ label: 'CRÍTICOS', icon: 'warning', tone: 'red', supporting: 'Abertos' }, { label: 'ATENÇÃO', icon: 'warning', tone: 'orange', supporting: 'Abertos' }, { label: 'INFORMATIVOS', icon: 'help', tone: 'blue', supporting: 'Abertos' }, { label: 'RESOLVIDOS 7 DIAS', icon: 'reconcile', tone: 'green', supporting: 'Histórico' }], middleTitle: 'ALERTAS CONSOLIDADOS', middleSubtitle: 'Todos os módulos', rightTitle: 'DISTRIBUIÇÃO DOS ALERTAS', rightSubtitle: 'Por módulo', lower: [{ label: 'CAIXA', icon: 'bank', tone: 'green', supporting: 'Alertas' }, { label: 'RECEBÍVEIS', icon: 'receivable', tone: 'blue', supporting: 'Alertas' }, { label: 'ESTOQUE', icon: 'box', tone: 'orange', supporting: 'Alertas' }, { label: 'PRODUÇÃO', icon: 'production', tone: 'blue', supporting: 'Alertas' }, { label: 'COMPRAS', icon: 'shopping', tone: 'purple', supporting: 'Alertas' }], alerts: ['Caixa previsto rompe reserva mínima', 'Estoque crítico afeta forecast e produção', 'Alertas sem responsável definido', 'Atualização das fontes requerida para remover STALE'], table: ['Módulo', 'Alerta', 'Impacto', 'Prioridade', 'Atualizado', 'Status'] },
}

function EmptyValue() { return <span className="mocap-empty-value">—</span> }
function MocapHeader({ config }: { config: ScreenConfig }) {
  const [exportOpen, setExportOpen] = useState(false)
  return <header className="mocap-header"><div className="mocap-heading"><span className="mocap-number">{config.number}</span><div><h1 aria-label={config.title === 'VISÃO EXECUTIVA' ? 'Visão Executiva' : config.title}>{config.title}</h1><p>{config.subtitle}</p></div></div><div className="mocap-header-actions"><div className="mocap-sync"><span>Posição: <strong>—</strong></span><span>Última sincronização: <strong>—</strong> <Icon icon="refresh" /></span></div><div className="mocap-export-wrap"><Tooltip id="metric.details"><button type="button" className="mocap-export" onClick={() => setExportOpen((open) => !open)}><Icon icon="export" />Exportar <span>⌄</span></button></Tooltip>{exportOpen && <div className="mocap-export-menu" role="menu"><Tooltip id="metric.details"><button type="button" disabled>Exportação indisponível sem dados confirmados</button></Tooltip></div>}</div></div></header>
}

function MocapCard({ card }: { card: Card }) {
  return <article className={`mocap-card tone-${card.tone} ${card.variant ? `variant-${card.variant}` : ''}`}><div className="mocap-card-icon"><Icon icon={card.icon} /></div><div className="mocap-card-body"><Tooltip id="metric.details"><span className="mocap-card-label">{card.label}</span></Tooltip>{card.variant === 'minimum-balance' ? <div className="mocap-minimum-values"><div><strong>30 dias</strong><b>—</b><span>Em: —</span><small>Folga: —</small></div><div><strong>60 dias</strong><b>—</b><span>Em: —</span><small>Folga: —</small></div></div> : <><EmptyValue />{card.supporting && <span className="mocap-card-support">{card.supporting}</span>}</>}<Tooltip id="metric.details"><button type="button" className="mocap-card-action">{card.variant === 'minimum-balance' ? 'Ver detalhes' : 'Ver detalhes'} <span>⌄</span></button></Tooltip></div></article>
}

function EmptyChart({ title }: { title: string }) {
  return <section className="mocap-panel mocap-chart-panel"><div className="mocap-panel-heading"><div><Icon icon="calendar" /><div><h2>{title}</h2><p>Sem série confirmada</p></div></div></div><div className="mocap-chart-legend"><span className="legend-green">●</span> Entradas <span className="legend-red">●</span> Saídas <span className="legend-blue">━●</span> Saldo projetado</div><div className="mocap-chart-empty"><div className="mocap-grid-lines"><i /><i /><i /><i /></div><span>Sem dados confirmados</span></div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver fluxo completo <span>→</span></button></Tooltip></section>
}

function EmptyDistribution({ title, subtitle }: { title: string; subtitle: string }) {
  return <section className="mocap-panel mocap-distribution"><div className="mocap-panel-heading"><div><Icon icon="pie" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-donut-wrap"><div className="mocap-donut"><span>Sem dados</span></div><div className="mocap-legend-list"><span><i className="tone-dot dot-teal" />Confirmado <b>—</b></span><span><i className="tone-dot dot-blue" />Provisório <b>—</b></span><span><i className="tone-dot dot-orange" />Pendente <b>—</b></span><span><i className="tone-dot dot-purple" />Divergente <b>—</b></span></div></div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver detalhes <span>→</span></button></Tooltip></section>
}

function EmptyTable({ title, subtitle, columns }: { title: string; subtitle: string; columns: string[] }) {
  return <section className="mocap-panel mocap-table-panel"><div className="mocap-panel-heading"><div><Icon icon="calendar" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody><tr><td colSpan={columns.length}><span>Sem dados confirmados</span></td></tr></tbody></table></div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver detalhes <span>→</span></button></Tooltip></section>
}

function EmptyRightPanel({ title, subtitle }: { title: string; subtitle: string }) {
  return <section className="mocap-panel mocap-right-empty"><div className="mocap-panel-heading"><div><Icon icon="pie" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-right-grid"><div><Icon icon="calendar" /><strong>Período</strong><EmptyValue /></div><div><Icon icon="warning" /><strong>Status</strong><span>Sem dados confirmados</span></div><div><Icon icon="chart" /><strong>Regra</strong><span>Aguardando fonte oficial</span></div><div><Icon icon="refresh" /><strong>Atualização</strong><EmptyValue /></div></div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver detalhes <span>→</span></button></Tooltip></section>
}

function EmptyCriticalPanel({ title, subtitle }: { title: string; subtitle: string }) {
  return <section className="mocap-panel mocap-critical-panel"><div className="mocap-panel-heading"><div><Icon icon="clock" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-critical-grid"><div><Icon icon="calendar" /><span>Período</span><strong>—</strong></div><div><Icon icon="trend" /><span>Saídas</span><strong>—</strong></div><div><Icon icon="trend" /><span>Entradas</span><strong>—</strong></div><div><Icon icon="money" /><span>Reserva mínima</span><strong>—</strong></div></div><div className="mocap-critical-warning"><Icon icon="warning" />Posição de caixa da semana: <b>SEM DADOS</b></div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver detalhes <span>→</span></button></Tooltip></section>
}

function EmptyCalculationPanel({ title, subtitle }: { title: string; subtitle: string }) {
  const rows = ['Resultado Líquido DRE', '(-) Valor já aplicado CDI Plus', 'Caixa consolidado', 'Reserva mínima', 'Saldo transferível', 'Capacidade de investimento']
  return <section className="mocap-panel mocap-calculation-panel"><div className="mocap-panel-heading"><div><Icon icon="calculator" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-calc-rows">{rows.map((row, index) => <div key={row} className={index === rows.length - 1 ? 'emphasis' : ''}><span>{row}</span><strong>—</strong></div>)}</div><Tooltip id="metric.details"><button type="button" className="mocap-link" disabled>Ver memória de cálculo <span>→</span></button></Tooltip></section>
}

function EmptyRulesPanel({ title, subtitle }: { title: string; subtitle: string }) {
  return <section className="mocap-panel mocap-rules-panel"><div className="mocap-panel-heading"><div><Icon icon="document" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-rules-grid"><div><Icon icon="chart" /><span>Fonte do lucro<strong>DRE Majucau</strong></span></div><div><Icon icon="wallet" /><span>Reserva mínima<strong>—</strong></span></div><div><Icon icon="settings" /><span>PMR / PMP / PME<strong>Diagnóstico</strong></span></div><div><Icon icon="clock" /><span>Semana crítica<strong>OPEN</strong></span></div></div><div className="mocap-rules-warning"><Icon icon="warning" />O DEV não define sozinho a posição do caixa da semana crítica</div><Tooltip id="settings.open"><button type="button" className="mocap-link" disabled>Ver parâmetros <span>→</span></button></Tooltip></section>
}

function EmptyMarketPanel({ title, subtitle }: { title: string; subtitle: string }) {
  const cards: Array<[MockupIcon, string, string]> = [['trend', 'COTAÇÃO INTERNACIONAL', 'Sem cotação confirmada'], ['warning', 'ALERTA CLIMÁTICO', 'Aguardando fonte'], ['leaf', 'SAFRA 2026/2027', 'Aguardando fonte'], ['flow', 'CÂMBIO (USD/BRL)', 'Aguardando fonte']]
  return <section className="mocap-panel mocap-market-panel"><div className="mocap-panel-heading"><div><Icon icon="leaf" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-market-grid">{cards.map(([icon, label, value]) => <div key={label} className="mocap-market-card"><Icon icon={icon} /><strong>{label}</strong><b>{value}</b><span>Fonte oficial pendente</span></div>)}</div></section>
}

function EmptyRiskPanel({ title, subtitle }: { title: string; subtitle: string }) {
  return <section className="mocap-panel mocap-risk-panel"><div className="mocap-panel-heading"><div><Icon icon="pie" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-risk-gauge"><div className="mocap-risk-arc"><span>Risco<strong>SEM DADOS</strong></span></div><div className="mocap-risk-legend"><span><i className="dot-red" />Alto</span><span><i className="dot-yellow" />Médio</span><span><i className="dot-green" />Baixo</span></div></div></section>
}

function EmptyMetadataPanel({ title, subtitle }: { title: string; subtitle: string }) {
  const rows = ['Versão ativa', 'Gerado em', 'Janela de treino', 'Bias', 'MAE', 'Modelo', 'Status']
  return <section className="mocap-panel mocap-metadata-panel"><div className="mocap-panel-heading"><div><Icon icon="document" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-metadata-table">{rows.map((row) => <div key={row}><span>{row}</span><strong>—</strong></div>)}</div><span className="mocap-metadata-note">ⓘ Venda ≠ Demanda</span></section>
}

function EmptyImpactTable({ title, subtitle, columns }: { title: string; subtitle: string; columns: string[] }) {
  return <section className="mocap-panel mocap-impact-panel"><div className="mocap-panel-heading"><div><Icon icon="box" /><div><h2>{title}</h2><p>{subtitle}</p></div></div></div><div className="mocap-table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody><tr><td colSpan={columns.length}><span>Sem dados confirmados</span></td></tr></tbody></table></div></section>
}

function EmptyPurchaseTable({ columns }: { columns: string[] }) {
  return <section className="mocap-panel mocap-purchase-panel"><div className="mocap-panel-heading"><div><Icon icon="shopping" /><div><h2>COMPRAS RECOMENDADAS</h2><p>Com base em forecast, produção, estoque, lead time e mercado</p></div></div><div className="mocap-table-actions"><button type="button" disabled>Próximos 60 dias⌄</button><button type="button" disabled>Todos os insumos⌄</button><button type="button" disabled>Gerar pedidos</button></div></div><div className="mocap-table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody><tr><td colSpan={columns.length}><span>Sem dados confirmados</span></td></tr></tbody></table></div></section>
}

function AlertPanel({ messages, onNavigate }: { messages: string[]; onNavigate?: (screen: MockupScreenKey) => void }) {
  return <section className="mocap-alerts"><div className="mocap-alerts-heading"><Icon icon="warning" /><h2>ALERTAS IMPORTANTES</h2></div><div className="mocap-alert-grid">{messages.map((message, index) => <article key={message} className={`mocap-alert alert-${index % 4}`}><div className="mocap-alert-icon"><Icon icon={index === 0 ? 'warning' : index === 1 ? 'document' : index === 2 ? 'clock' : 'refresh'} /></div><div><strong>{message}</strong><span>Sem dados confirmados</span>{index === 0 && onNavigate ? <Tooltip id="notice.integrations"><button type="button" onClick={() => onNavigate('integrations')}>Ir para Integrações <span>→</span></button></Tooltip> : <Tooltip id="metric.details"><button type="button" disabled>Ver detalhes <span>→</span></button></Tooltip>}</div></article>)}</div></section>
}

export function MockupDashboard({ screen, onNavigate }: { screen: MockupScreenKey; onNavigate?: (screen: MockupScreenKey) => void }) {
  const config = configs[screen === 'integrations' ? 'executive' : screen]
  const middleLeft = config.layout === 'market' ? <EmptyMarketPanel title={config.middleTitle} subtitle={config.middleSubtitle} /> : config.layout === 'calculation' ? <EmptyCalculationPanel title={config.middleTitle} subtitle={config.middleSubtitle} /> : config.table ? <EmptyTable title={config.middleTitle} subtitle={config.middleSubtitle} columns={config.table} /> : config.chart ? <EmptyChart title={config.middleTitle} /> : <EmptyRightPanel title={config.middleTitle} subtitle={config.middleSubtitle} />
  const middleRight = config.layout === 'market' ? <EmptyRiskPanel title={config.rightTitle} subtitle={config.rightSubtitle} /> : config.layout === 'critical' ? <EmptyCriticalPanel title={config.rightTitle} subtitle={config.rightSubtitle} /> : config.layout === 'calculation' ? <EmptyRulesPanel title={config.rightTitle} subtitle={config.rightSubtitle} /> : config.layout === 'forecast' ? <EmptyMetadataPanel title={config.rightTitle} subtitle={config.rightSubtitle} /> : <EmptyDistribution title={config.rightTitle} subtitle={config.rightSubtitle} />
  const lower = config.layout === 'market' ? <><EmptyPurchaseTable columns={config.table ?? []} /><section className="mocap-market-lower"><EmptyChart title="NECESSIDADE DE COMPRA (TONELADAS)" /><EmptyDistribution title="ORIGEM DA NECESSIDADE" subtitle="Produção e estoque" /><AlertPanel messages={config.alerts} onNavigate={onNavigate} /></section></> : config.layout === 'forecast' ? <><EmptyImpactTable title="ITENS DE MAIOR IMPACTO" subtitle="SKUs com maior desvio entre forecast e realizado" columns={config.table ?? []} /><section className="mocap-lower-cards">{config.lower.map((card) => <MocapCard key={card.label} card={card} />)}</section></> : <section className="mocap-lower-cards">{config.lower.map((card) => <MocapCard key={card.label} card={card} />)}</section>
  return <div className="mocap-page"><MocapHeader config={config} /><section className="mocap-top-cards">{config.cards.map((card) => <MocapCard key={card.label} card={card} />)}</section><section className={`mocap-middle ${config.layout ? `layout-${config.layout}` : ''}`}>{middleLeft}{middleRight}</section>{lower}{config.layout !== 'market' && <AlertPanel messages={config.alerts} onNavigate={onNavigate} />}</div>
}
