export const tooltipCatalog = {
  'treasury.openingBalance': 'Dinheiro conciliado disponível no início do dia. Ele deve ser igual ao saldo final confirmado do dia anterior.',
  'treasury.todayClosing': 'Estimativa do dinheiro ao final de hoje, considerando o saldo inicial e os movimentos previstos ou realizados do dia.',
  'treasury.balance30': 'Estimativa do dinheiro disponível ao final dos próximos 30 dias no cenário selecionado.',
  'treasury.balance60': 'Estimativa do dinheiro disponível ao final dos próximos 60 dias no cenário selecionado.',
  'treasury.minimum60': 'Menor saldo diário encontrado na projeção de 60 dias. Abra o card para ver a data e o que causou esse valor.',
  'treasury.minimumReserve': 'Valor mínimo que deve permanecer disponível para proteger a operação. Alterações precisam de aprovação.',
  'treasury.maximumInvestment': 'Cálculo provisório do limite de aplicação segundo a regra proposta. O card permanece bloqueado até a fórmula ou a planilha de referência ser aprovada.',
  'treasury.scenario': 'Conjunto de premissas usado na projeção. Trocar o cenário não altera os dados realizados.',
  'treasury.referenceDate': 'Data usada como início dos saldos, recebíveis, obrigações e projeções exibidos.',
  'receivables.b2cNuvem': 'Vendas futuras ao consumidor vindas exclusivamente da fonte Nuvem. Taxa, líquido e data só são confirmados quando a fonte oficial os fornece.',
  'receivables.b2bBling': 'Títulos futuros classificados como vendas entre empresas no Bling. Casos sem classificação aprovada ficam fora do total confirmado.',
  'receivables.total': 'Soma do B2C futuro da Nuvem com o B2B futuro do Bling. O B2C do Bling não é somado.',
  'receivables.receivedMonth': 'Valores efetivamente recebidos no mês conforme a situação paga ou recebida no Bling.',
  'payables.total': 'Saldo de obrigações ainda abertas no Bling para o período e filtros selecionados.',
  'payables.overdue': 'Obrigações com saldo aberto e vencimento anterior à data de referência.',
  'payables.paidMonth': 'Valores efetivamente pagos no mês conforme os registros do Bling.',
  'result.drePnl': 'Resultado de receitas, custos e despesas calculado pelo Majucau. Diferenças exigem ajuste identificado e aprovado.',
  'result.ebitda': 'Resultado operacional antes de juros, impostos, depreciação e amortização, conforme a regra contábil aprovada.',
  'planning.budgetActual': 'Compara o valor planejado com o que realmente ocorreu. Favorável ou desfavorável depende da natureza da linha.',
  'planning.forecast': 'Previsão versionada baseada em premissas e cenário. Uma nova versão não apaga o histórico.',
  'management.workingCapital': 'Diferença entre ativos e obrigações de curto prazo conforme o plano de contas aprovado.',
  'management.alerts': 'Situações financeiras ou operacionais que precisam de atenção. Abra para ver a causa, a fonte e a ação esperada.',
  'status.confirmed': 'O dado foi conciliado com a fonte oficial e passou pelas regras de validação.',
  'status.provisional': 'O valor pode mudar porque o período ou a fonte ainda não foi conciliado.',
  'status.noSource': 'Nenhuma fonte oficial foi conectada; por isso não há valor confirmado para exibir.',
  'integration.connectionStatus': 'Estado atual da autorização e da última comunicação com a integração.',
  'source.lastUpdate': 'Última vez em que esta fonte terminou a sincronização com sucesso.',
  'nav.executive': 'Abre a visão executiva com os indicadores oficiais e seus estados de confirmação.',
  'nav.integrations': 'Abre as integrações para conectar fontes oficiais de dados.',
  'settings.open': 'Abre as configurações de integrações e segurança.',
  'metric.details': 'Abre a composição do valor, a regra usada e os registros de origem quando houver dados confirmados.',
  'notice.integrations': 'As fontes oficiais são conectadas nas configurações de integrações.',
  'filter.scenario': 'Troca as premissas da projeção sem alterar os valores realizados.',
  'filter.referenceDate': 'Data usada como início dos saldos, recebíveis, obrigações e projeções exibidos.',
  'field.value': 'Campo de configuração da integração. O conteúdo não é armazenado no frontend.',
  'action.test': 'Verifica a conexão de forma somente leitura. Nesta fundação G1, o worker ainda não está conectado.',
  'action.reconnect': 'Solicita nova autorização. Nesta fundação G1, o worker ainda não está conectado.',
  'action.disconnect': 'Solicita remoção segura da autorização. Nesta fundação G1, o worker ainda não está conectado.',
  'action.syncNow': 'Solicita uma sincronização. Nesta fundação G1, o worker ainda não está conectado.',
  'dialog.close': 'Fecha esta janela sem executar uma ação.',
  'dialog.cancel': 'Fecha esta janela sem executar uma ação.',
  'dialog.continue': 'A ação está indisponível enquanto a conexão com o worker não existir.',
  'bling.clientId': 'Identificador público do aplicativo cadastrado no Bling.',
  'bling.clientSecret': 'Chave secreta do aplicativo Bling. Ela é protegida no Windows e não volta a ser exibida depois de salva.',
  'bling.redirectUri': 'Endereço registrado no Bling para concluir a autorização.',
  'bling.connect': 'Abre o Bling no navegador para autorizar a leitura dos dados.',
  'bling.test': 'Verifica a autorização com uma leitura pequena, sem alterar dados no Bling.',
  'bling.reconnect': 'Faz uma nova autorização quando a anterior expirou ou foi revogada.',
  'bling.disconnect': 'Remove os tokens salvos e interrompe novas sincronizações. Os dados já importados são preservados.',
  'bling.syncNow': 'Solicita uma nova leitura. Registros repetidos não devem ser duplicados.',
  'nuvemshop.appId': 'Identificador do aplicativo cadastrado na Nuvemshop.',
  'nuvemshop.clientSecret': 'Chave secreta usada para concluir a autorização. Ela fica protegida no Windows.',
  'nuvemshop.redirectUri': 'Endereço HTTPS registrado para receber o retorno da autorização.',
  'nuvemshop.connect': 'Abre a Nuvemshop no navegador e inicia uma autorização temporária e protegida.',
  'nuvemshop.test': 'Confirma que a loja e a permissão de pedidos podem ser lidas sem alterar dados.',
  'nuvemshop.reconnect': 'Faz uma nova autorização da loja quando a anterior expirou ou foi revogada.',
  'nuvemshop.disconnect': 'Remove os tokens salvos e preserva os dados já importados.',
  'nuvemshop.syncNow': 'Solicita uma nova leitura da loja sem duplicar registros.',
  'nuvempago.availability': 'A confirmação financeira depende de uma API ou arquivo oficial com taxa, líquido e data de repasse.',
  'nuvempago.partial': 'Pedidos e status podem estar disponíveis, mas faltam dados oficiais para confirmar o recebimento líquido.',
  'nuvempago.pricing': 'Tarifas aprovadas para estimativa. Elas não substituem taxa efetiva, líquido ou data de liquidação vindos de um ledger oficial.',
  'chart.projected': 'Valores futuros estimados pelo cenário selecionado.',
} as const
export type TooltipId = keyof typeof tooltipCatalog
