// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBlingOAuthStatus(arg1) {
  return window['go']['main']['App']['GetBlingOAuthStatus'](arg1);
}

export function GetBootstrapState() {
  return window['go']['main']['App']['GetBootstrapState']();
}

export function ImportBlingReceipts(arg1) {
  return window['go']['main']['App']['ImportBlingReceipts'](arg1);
}

export function PreviewBlingReceipts(arg1) {
  return window['go']['main']['App']['PreviewBlingReceipts'](arg1);
}

export function SaveBlingConfig(arg1) {
  return window['go']['main']['App']['SaveBlingConfig'](arg1);
}

export function SaveNuvemshopConfig(arg1) {
  return window['go']['main']['App']['SaveNuvemshopConfig'](arg1);
}

export function StartBlingOAuth() {
  return window['go']['main']['App']['StartBlingOAuth']();
}

export function SyncBling(arg1) {
  return window['go']['main']['App']['SyncBling'](arg1);
}

export function TestBlingConnection() {
  return window['go']['main']['App']['TestBlingConnection']();
}
