// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {application} from '../models';

export function GetBootstrapState():Promise<main.BootstrapState>;

export function ImportBlingReceipts(arg1:string):Promise<application.BlingReceiptImportResult>;

export function PreviewBlingReceipts(arg1:string):Promise<application.BlingReceiptImportPreview>;

export function SaveBlingConfig(arg1:application.BlingConfigRequest):Promise<application.BlingConfigResponse>;
