// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapState() {
  return window['go']['main']['App']['GetBootstrapState']();
}

export function ImportBlingReceipts(arg1) {
  return window['go']['main']['App']['ImportBlingReceipts'](arg1);
}

export function PreviewBlingReceipts(arg1) {
  return window['go']['main']['App']['PreviewBlingReceipts'](arg1);
}
