// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {main} from '../models';

export function GetBlingOAuthStatus(arg1:string):Promise<application.BlingOAuthStatusResponse>;

export function GetBootstrapState():Promise<main.BootstrapState>;

export function GetDashboardSnapshot():Promise<application.DashboardSnapshot>;

export function ImportBlingReceipts(arg1:string):Promise<application.BlingReceiptImportResult>;

export function PreviewBlingReceipts(arg1:string):Promise<application.BlingReceiptImportPreview>;

export function SaveBlingConfig(arg1:application.BlingConfigRequest):Promise<application.BlingConfigResponse>;

export function SaveNuvemshopConfig(arg1:application.NuvemshopConfigRequest):Promise<application.NuvemshopConfigResponse>;

export function StartBlingOAuth():Promise<application.BlingOAuthStartResponse>;

export function SyncBling(arg1:application.BlingSyncRequest):Promise<application.BlingSyncResponse>;

export function TestBlingConnection():Promise<application.BlingOAuthTestResponse>;

